# Final Project Cleaning

Iris Qiu

## Topic 
**The analysis of the hazmat spills happened in California, especially the city of Richmond, CA, from 2010 to 6/1/2023.**

- **Dataset**: Hazmat Spill Reports - A dataset presents significant release or threatened release of a hazardous material in California from 2010 to 6/1/2023.
https://www.caloes.ca.gov/office-of-the-director/operations/response-operations/fire-rescue/hazardous-materials/spill-release-reporting/
(The dataset on the California Governor's Office of Emergency Services website linked above are separate by years, and I manually merge them into one Excel sheet. I have checked that all the columns headings are the same.)
- **Why I chose this topic**:
As I was assigned to report on Richmond this semester for J200, during several turns of interviews with the residents, I found out that the refinery has a great impact on their lives. Many residents said that they were born with asthma and have witnessed many flaring events. Thus, I would like to explore the trend of spills happened throught out the decades and its comparison between Richmond and other cities in California.

In [1]:
import pandas as pd

In [2]:
spills = pd.read_excel('Hazmat Spill Reports.xlsx', engine='openpyxl')

## View Data

Soo told me the following method to view all the columns in the dataframe

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
spills

Control#       Notified Date   
0       '23-3596 2023-06-01 13:30:00  \
1       '23-3595 2023-06-01 13:11:00   
2       '23-3594 2023-06-01 13:15:00   
3       '23-3592 2023-06-01 12:07:00   
4       '23-3591 2023-06-01 11:55:00   
...          ...                 ...   
102121  '10-7993 2010-12-31 13:20:00   
102122  '10-7994 2010-12-31 16:13:00   
102123  '10-7995 2010-12-31 17:13:00   
102124  '10-7996 2010-12-31 17:22:00   
102125  '10-7997 2010-12-31 18:20:00   

                                            Agency   
0                     Green Clean Pressure Washing  \
1                                             UPRR   
2                                    CHP - Barstow   
3                     California Northern Railroad   
4                                              NRC   
...                                            ...   
102121                                        CURA   
102122                                 Veeder Root   
102123  Victor Valley Waste Water Reclamation Auth   
102124                                Red Bluff FD   
102125                                         NRC   

                            1. Substance 1. Quantity 1. Measure    1. Type   
0                                Coolant           7     Gal(s)  PETROLEUM  \
1                            diesel fuel         100     Gal(s)  PETROLEUM   
2                      Corrosive Liquid           16       Lbs.   CHEMICAL   
3                            Bridge Fire           1        NaN      OTHER   
4                       Unknown Material     Unknown        NaN      VAPOR   
...                                  ...         ...        ...        ...   
102121                            Diesel          50     Gal(s)  PETROLEUM   
102122                          Gasoline           3     Gal(s)  PETROLEUM   
102123                      Sewage - Raw        3040     Gal(s)     SEWAGE   
102124  Oil - unk type, mixed with water          50     Gal(s)  PETROLEUM   
102125                       Unknown Oil     Unknown      Sheen  PETROLEUM   

                1.  Other 1. Pipeline 1. Vessel >= 300 Tons 2. Substance   
0                     NaN          No                    No          NaN  \
1                     NaN          No                    No          NaN   
2                     NaN          No                    No          NaN   
3                    Fire          No                    No          NaN   
4                     NaN          No                    No          NaN   
...                   ...         ...                   ...          ...   
102121                NaN         NaN                   NaN          NaN   
102122                NaN         NaN                   NaN          NaN   
102123                NaN         NaN                   NaN          NaN   
102124                NaN         NaN                   NaN          NaN   
102125  Faint diesel odor         NaN                   NaN          NaN   

       2. Quantity 2. Measure 2. Type 2.  Other 2.  Pipeline   
0              NaN        NaN     NaN       NaN           No  \
1              NaN        NaN     NaN       NaN           No   
2              NaN        NaN     NaN       NaN           No   
3              NaN        NaN     NaN       NaN           No   
4              NaN        NaN     NaN       NaN           No   
...            ...        ...     ...       ...          ...   
102121         NaN        NaN     NaN       NaN          NaN   
102122         NaN        NaN     NaN       NaN          NaN   
102123         NaN        NaN     NaN       NaN          NaN   
102124         NaN        NaN     NaN       NaN          NaN   
102125         NaN        NaN     NaN       NaN          NaN   

       2. Vessel >= 300 Tons 3. Substance 3. Quantity 3. Measure 3. Type   
0                         No          NaN         NaN        NaN     NaN  \
1                         No          NaN         NaN        NaN     NaN   
2                         No   

In [5]:
spills.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102126 entries, 0 to 102125
Data columns (total 50 columns):
 #   Column                   Non-Null Count   Dtype         
---  ------                   --------------   -----         
 0   Control#                 102126 non-null  object        
 1   Notified Date            102126 non-null  datetime64[ns]
 2   Agency                   102046 non-null  object        
 3   1. Substance             101980 non-null  object        
 4   1. Quantity              96744 non-null   object        
 5   1. Measure               89225 non-null   object        
 6   1. Type                  102123 non-null  object        
 7   1.  Other                6847 non-null    object        
 8   1. Pipeline              89670 non-null   object        
 9   1. Vessel >= 300 Tons    93814 non-null   object        
 10  2. Substance             3339 non-null    object        
 11  2. Quantity              3313 non-null    object        
 12  2. Measure      

## Drop Duplicates

By using `df.copy()` to create a copy of the original dataframe, I can compare the edited dataframe with the original dataframe if I run into any probelms. 

In [6]:
hazmat_spills = spills.copy()

In [7]:
hazmat_spills['Control#'].nunique()

102035

In [8]:
len(hazmat_spills)

102126

In [9]:
len(hazmat_spills) - hazmat_spills['Control#'].nunique()

91

In [10]:
hazmat_spills[hazmat_spills.duplicated()]

Control#       Notified Date   
4351   '22-6782 2022-11-17 12:58:00  \
6452   '22-4522 2022-08-07 11:42:00   
6453   '22-4522 2022-08-07 11:42:00   
6454   '22-4522 2022-08-07 11:42:00   
6456   '22-4522 2022-08-07 11:42:00   
6457   '22-4522 2022-08-07 11:42:00   
6458   '22-4522 2022-08-07 11:42:00   
6459   '22-4522 2022-08-07 11:42:00   
6460   '22-4522 2022-08-07 11:42:00   
9824   '22-0986 2022-02-20 09:04:00   
20701  '20-4200 2020-08-06 16:01:00   
23347  '20-1423 2020-03-11 15:23:00   
23348  '20-1423 2020-03-11 15:23:00   
27173  '19-5750 2019-09-05 12:17:00   
30517  '19-2212 2019-04-03 12:36:00   
31108  '19-1586 2019-03-06 14:36:00   
31319  '19-1371 2019-02-26 16:25:00   
40611  '18-0500 2018-01-23 12:18:00   
52901  '16-4683 2016-08-01 19:52:00   
53097  '16-4477 2016-07-23 18:42:00   
54043  '16-3473 2016-06-09 09:57:00   
60633  '15-3400 2015-06-16 11:56:00   
60817  '15-3594 2015-06-25 05:43:00   
60958  '15-3746 2015-07-01 10:38:00   
60959  '15-3746 2015-07-01 10:38:00   
60960  '15-3746 2015-07-01 10:38:00   
60961  '15-3746 2015-07-01 10:38:00   
60962  '15-3746 2015-07-01 10:38:00   
61637  '15-4437 2015-08-01 08:18:00   
63758  '15-6658 2015-11-11 11:27:00   
64699         ' 2014-01-20 09:52:00   
64700         ' 2014-01-20 09:52:00   
64701         ' 2014-01-20 09:52:00   
66331  '14-1677 2014-03-19 20:04:00   
69411  '14-4946 2014-09-03 11:16:00   
69413  '14-4946 2014-09-03 11:16:00   
73547  '13-1860 2013-03-27 13:44:00   
73548  '13-1860 2013-03-27 13:44:00   
74015  '13-2344 2013-04-19 10:34:00   
74016  '13-2344 2013-04-19 10:34:00   
96240  '10-1862 2010-03-18 05:02:00   

                                           Agency   
4351                 Lake County Special District  \
6452    San Joaquin facilities management company   
6453    San Joaquin facilities management company   
6454    San Joaquin facilities management company   
6456    San Joaquin facilities management company   
6457    San Joaquin facilities management company   
6458    San Joaquin facilities management company   
6459    San Joaquin facilities management company   
6460    San Joaquin facilities management company   
9824                                          NRC   
20701                                        PG&E   
23347                                         CHP   
23348                                         CHP   
27173                                   SoCal Gas   
30517                   City of Lodi Public Works   
31108                  Monterey Health Inspector    
31319                          City of Yountville   
40611                                          BP   
52901                                         CHP   
53097                                         NRC   
54043                                Bishop - CHP   
60633         Ventura County Environmental Health   
60817                                 Phillips 66   
60958                        Contra Costa Sheriff   
60959                        Contra Costa Sheriff   
60960                        Contra Costa Sheriff   
60961                        Contra Costa Sheriff   
60962                        Contra Costa Sheriff   
61637                        Long Beach Fire Dept   
63758    Central Contra Costa Sanitation District   
64699                                         NRC   
64700                                         NRC   
64701                                         NRC   
66331                                         NRC   
69411                 LAUSD Env health and Safety   
69413                 LAUSD Env health and Safety   
73547                                     Citizen   
73548                                     Citizen   
74015  US Navy - Asst Safety Officer - USS Nimitz   
74016  US Navy - Asst Safety Officer - USS Nimitz   
96240                          US Navy Point Loma   

                                            1. Substance 1. Quantity   
4351                                          Raw Sewage          58 

I noticed that there are some rows that the Control# is ' or '-, but they are probably not duplicates, so I need to ensure that I don't drop those.

### Clean blank_cases

To do this, I will first subset and drop all the rows that the Control# is ' or '- (which I called blank_cases) from the dataframe and I will check duplicates for each of them. 


In [11]:
blank_cases = hazmat_spills[(hazmat_spills["Control#"] == "'") | (hazmat_spills["Control#"] == "'-")].copy()
blank_cases

Control#       Notified Date                                     Agency   
3450        '- 2023-02-16 19:36:00  City of San Diego Waste Water Collections  \
3451         ' 2023-05-24 09:22:00                 Delete (Duplicate Report)    
5294         ' 2022-09-30 10:38:00                                        NRC   
17928       '- 2021-10-31 14:34:00             San Diego Environmental Health   
17929        ' 2021-10-21 18:06:00                                        NRC   
17930        ' 2021-10-29 14:06:00                                    afdasdf   
17931        ' 2021-12-11 17:18:00                                       IBWC   
24727       '- 2020-05-22 15:14:00                              Southwest Gas   
24728        ' 2020-06-08 12:41:00                                      TEST    
24729        ' 2020-06-10 09:05:00                                     Delete   
24730        ' 2020-11-18 14:48:00                                        NaN   
24731        ' 2020-11-25 12:25:00                                        xxx   
24732        ' 2020-12-08 13:42:00                          Verisk 3E Company   
24733        ' 2020-12-09 16:09:00                                        NRC   
24734        ' 2020-12-18 20:52:00                                       NRC    
24735        ' 2020-12-24 08:44:00                                        NaN   
26643        ' 2019-10-01 09:30:00             Sacramento Area Sewer District   
32655        ' 2019-10-07 15:29:00                               So Cal Gas,    
32656        ' 2019-10-11 13:29:00                                        NaN   
32657        ' 2019-10-11 13:45:00                                        NaN   
32658        ' 2019-10-12 01:35:00                                       UPRR   
32659        ' 2019-11-12 12:38:00                              Whit O Briens   
32660        ' 2019-12-11 16:26:00                                        NRC   
64698        ' 2014-01-20 09:52:00                                        NRC   
64699        ' 2014-01-20 09:52:00                                        NRC   
64700        ' 2014-01-20 09:52:00                                        NRC   
64701        ' 2014-01-20 09:52:00                                        NRC   
79371        ' 2012-08-16 03:28:00                      City of Newport Beach   

                       1. Substance                        1. Quantity   
3450                         Sewage                            Unknown  \
3451                         Delete                             Delete   
5294            Unknown Oil (Sheen)  Length: 20  Feet / Width: 5  Feet   
17928                     Motor Oil                                 50   
17929  HYDRAULIC OIL(rainbow sheen)                        20FT x 15FT   
17930                        adfadf                                  2   
17931                        Sewage                              50000   
24727                   Natural Gas                            unknown   
24728                         TEST                                   3   
24729                        Delete                            Unknown   
24730                           NaN                                NaN   
24731                           xxx                                 10   
24732             R507A Refrigerant                                175   
24733             Anhydrous Ammonia                                300   
24734                           NaN                            Unknown   
24735                           NaN                                NaN   
26643                        Sewage                               1100   
32655                   Natural Gas                            Unknown   
32656                           NaN                                NaN   
32657                          XXXX                                  x   
32658                        Diesel                            Unknown   
32659               Hydrauli

In [12]:
hazmat_spills = hazmat_spills.drop(blank_cases.index, axis=0)

In [13]:
hazmat_spills

Control#       Notified Date   
0       '23-3596 2023-06-01 13:30:00  \
1       '23-3595 2023-06-01 13:11:00   
2       '23-3594 2023-06-01 13:15:00   
3       '23-3592 2023-06-01 12:07:00   
4       '23-3591 2023-06-01 11:55:00   
...          ...                 ...   
102121  '10-7993 2010-12-31 13:20:00   
102122  '10-7994 2010-12-31 16:13:00   
102123  '10-7995 2010-12-31 17:13:00   
102124  '10-7996 2010-12-31 17:22:00   
102125  '10-7997 2010-12-31 18:20:00   

                                            Agency   
0                     Green Clean Pressure Washing  \
1                                             UPRR   
2                                    CHP - Barstow   
3                     California Northern Railroad   
4                                              NRC   
...                                            ...   
102121                                        CURA   
102122                                 Veeder Root   
102123  Victor Valley Waste Water Reclamation Auth   
102124                                Red Bluff FD   
102125                                         NRC   

                            1. Substance 1. Quantity 1. Measure    1. Type   
0                                Coolant           7     Gal(s)  PETROLEUM  \
1                            diesel fuel         100     Gal(s)  PETROLEUM   
2                      Corrosive Liquid           16       Lbs.   CHEMICAL   
3                            Bridge Fire           1        NaN      OTHER   
4                       Unknown Material     Unknown        NaN      VAPOR   
...                                  ...         ...        ...        ...   
102121                            Diesel          50     Gal(s)  PETROLEUM   
102122                          Gasoline           3     Gal(s)  PETROLEUM   
102123                      Sewage - Raw        3040     Gal(s)     SEWAGE   
102124  Oil - unk type, mixed with water          50     Gal(s)  PETROLEUM   
102125                       Unknown Oil     Unknown      Sheen  PETROLEUM   

                1.  Other 1. Pipeline 1. Vessel >= 300 Tons 2. Substance   
0                     NaN          No                    No          NaN  \
1                     NaN          No                    No          NaN   
2                     NaN          No                    No          NaN   
3                    Fire          No                    No          NaN   
4                     NaN          No                    No          NaN   
...                   ...         ...                   ...          ...   
102121                NaN         NaN                   NaN          NaN   
102122                NaN         NaN                   NaN          NaN   
102123                NaN         NaN                   NaN          NaN   
102124                NaN         NaN                   NaN          NaN   
102125  Faint diesel odor         NaN                   NaN          NaN   

       2. Quantity 2. Measure 2. Type 2.  Other 2.  Pipeline   
0              NaN        NaN     NaN       NaN           No  \
1              NaN        NaN     NaN       NaN           No   
2              NaN        NaN     NaN       NaN           No   
3              NaN        NaN     NaN       NaN           No   
4              NaN        NaN     NaN       NaN           No   
...            ...        ...     ...       ...          ...   
102121         NaN        NaN     NaN       NaN          NaN   
102122         NaN        NaN     NaN       NaN          NaN   
102123         NaN        NaN     NaN       NaN          NaN   
102124         NaN        NaN     NaN       NaN          NaN   
102125         NaN        NaN     NaN       NaN          NaN   

       2. Vessel >= 300 Tons 3. Substance 3. Quantity 3. Measure 3. Type   
0                         No          NaN         NaN        NaN     NaN  \
1                         No          NaN         NaN        NaN     NaN   
2                         No   

Now, the blank_cases are dropped from the dataframe. I will check if there are any duplicates within black_cases. Since they have the same Control#, I will use 'Notified Date' as identifier to check

In [14]:
blank_cases['Notified Date'].nunique()

25

In [15]:
len(blank_cases)

28

In [16]:
len(blank_cases) - blank_cases['Notified Date'].nunique()

3

In [17]:
blank_cases[blank_cases.duplicated()]

Control#       Notified Date Agency 1. Substance 1. Quantity 1. Measure   
64699        ' 2014-01-20 09:52:00    NRC          Gas         0.5     Gal(s)  \
64700        ' 2014-01-20 09:52:00    NRC          Gas         0.5     Gal(s)   
64701        ' 2014-01-20 09:52:00    NRC          Gas         0.5     Gal(s)   

         1. Type 1.  Other 1. Pipeline 1. Vessel >= 300 Tons 2. Substance   
64699  PETROLEUM       NaN          No                    No          NaN  \
64700  PETROLEUM       NaN          No                    No          NaN   
64701  PETROLEUM       NaN          No                    No          NaN   

      2. Quantity 2. Measure 2. Type 2.  Other 2.  Pipeline   
64699         NaN        NaN     NaN       NaN           No  \
64700         NaN        NaN     NaN       NaN           No   
64701         NaN        NaN     NaN       NaN           No   

      2. Vessel >= 300 Tons 3. Substance 3. Quantity 3. Measure 3. Type   
64699                    No          NaN         NaN        NaN     NaN  \
64700                    No          NaN         NaN        NaN     NaN   
64701                    No          NaN         NaN        NaN     NaN   

      3.  Other 3.  Pipeline 3.  Vessel >= 300 Tons   
64699       NaN           No                     No  \
64700       NaN           No                     No   
64701       NaN           No                     No   

                                             Description Contained Water?   
64699  Per NRC#1071643 "DISPENSER #9 SPILLED ROUGHLY ...       Yes     No  \
64700  Per NRC#1071643 "DISPENSER #9 SPILLED ROUGHLY ...       Yes     No   
64701  Per NRC#1071643 "DISPENSER #9 SPILLED ROUGHLY ...       Yes     No   

      Water Way        Location   City              County    Zip   
64699       NaN  1804 W 11TH ST  Tracy  San Joaquin County  95376  \
64700       NaN  1804 W 11TH ST  Tracy  San Joaquin County  95376   
64701       NaN  1804 W 11TH ST  Tracy  San Joaquin County  95376   

             Incident Date Time         Spill Site Site       CAUSE   
64699  2014-01-20 00:00:00  915  Merchant/Business  NaN  Mechanical  \
64700  2014-01-20 00:00:00  915  Merchant/Business  NaN  Mechanical   
64701  2014-01-20 00:00:00  915  Merchant/Business  NaN  Mechanical   

      CAUSE_Other Injuries YES/NO Injuries # Fatals YES/NO Fatals #   
64699         NaN              No        NaN            No      NaN  \
64700         NaN              No        NaN            No      NaN   
64701         NaN              No        NaN            No      NaN   

      Evacs YES/NO Evacs #            Cleanup   
64699           No     NaN  Responsible Party  \
64700           No     NaN  Responsible Party   
64701           No     NaN  Responsible Party   

                                  Admin Agency DOG #   
64699  San Joaquin County Environmental Health   NaN  \
64700  San Joaquin County Environmental Health   NaN   
64701  San Joaquin County Environmental Health   NaN   

                              Notification Area Drinking Water Impacted   
64699  AA/CUPA,DFG-OSPR,DTSC,RWQCB,US EPA,USFWS                     NaN  \
64700  AA/CUPA,DFG-OSPR,DTSC,RWQCB,US EPA,USFWS                     NaN   
64701  AA/CUPA,DFG-OSPR,DTSC,RWQCB,US EPA,USFWS                     NaN   

      Known Impact  
64699          NaN  
64700          NaN  
64701          NaN

There are three exact duplicates in the blank_cases!

In [18]:
blank_cases = blank_cases.drop_duplicates(subset=['Notified Date'])
blank_cases

Control#       Notified Date                                     Agency   
3450        '- 2023-02-16 19:36:00  City of San Diego Waste Water Collections  \
3451         ' 2023-05-24 09:22:00                 Delete (Duplicate Report)    
5294         ' 2022-09-30 10:38:00                                        NRC   
17928       '- 2021-10-31 14:34:00             San Diego Environmental Health   
17929        ' 2021-10-21 18:06:00                                        NRC   
17930        ' 2021-10-29 14:06:00                                    afdasdf   
17931        ' 2021-12-11 17:18:00                                       IBWC   
24727       '- 2020-05-22 15:14:00                              Southwest Gas   
24728        ' 2020-06-08 12:41:00                                      TEST    
24729        ' 2020-06-10 09:05:00                                     Delete   
24730        ' 2020-11-18 14:48:00                                        NaN   
24731        ' 2020-11-25 12:25:00                                        xxx   
24732        ' 2020-12-08 13:42:00                          Verisk 3E Company   
24733        ' 2020-12-09 16:09:00                                        NRC   
24734        ' 2020-12-18 20:52:00                                       NRC    
24735        ' 2020-12-24 08:44:00                                        NaN   
26643        ' 2019-10-01 09:30:00             Sacramento Area Sewer District   
32655        ' 2019-10-07 15:29:00                               So Cal Gas,    
32656        ' 2019-10-11 13:29:00                                        NaN   
32657        ' 2019-10-11 13:45:00                                        NaN   
32658        ' 2019-10-12 01:35:00                                       UPRR   
32659        ' 2019-11-12 12:38:00                              Whit O Briens   
32660        ' 2019-12-11 16:26:00                                        NRC   
64698        ' 2014-01-20 09:52:00                                        NRC   
79371        ' 2012-08-16 03:28:00                      City of Newport Beach   

                       1. Substance                        1. Quantity   
3450                         Sewage                            Unknown  \
3451                         Delete                             Delete   
5294            Unknown Oil (Sheen)  Length: 20  Feet / Width: 5  Feet   
17928                     Motor Oil                                 50   
17929  HYDRAULIC OIL(rainbow sheen)                        20FT x 15FT   
17930                        adfadf                                  2   
17931                        Sewage                              50000   
24727                   Natural Gas                            unknown   
24728                         TEST                                   3   
24729                        Delete                            Unknown   
24730                           NaN                                NaN   
24731                           xxx                                 10   
24732             R507A Refrigerant                                175   
24733             Anhydrous Ammonia                                300   
24734                           NaN                            Unknown   
24735                           NaN                                NaN   
26643                        Sewage                               1100   
32655                   Natural Gas                            Unknown   
32656                           NaN                                NaN   
32657                          XXXX                                  x   
32658                        Diesel                            Unknown   
32659               Hydraulic Fluid                                  3   
32660               Transformer Oil                                 10   
64698                           Gas                                0.5   
79371                        Sewage              

In [19]:
assert len(blank_cases) == blank_cases['Notified Date'].nunique()

Now, though the duplicates are all dropped, there are still some rows that seems to be meaningless. (e.g., row 3451 or row 24728) I will delete these one by one

In [20]:
blank_cases = blank_cases.drop(3451)

In [21]:
blank_cases = blank_cases.drop(24729)

In [22]:
blank_cases = blank_cases.drop(24730)

In [23]:
blank_cases = blank_cases.drop(24735)

In [24]:
blank_cases = blank_cases.drop(32656)

In [25]:
blank_cases = blank_cases.drop(32657)

In [26]:
blank_cases

Control#       Notified Date                                     Agency   
3450        '- 2023-02-16 19:36:00  City of San Diego Waste Water Collections  \
5294         ' 2022-09-30 10:38:00                                        NRC   
17928       '- 2021-10-31 14:34:00             San Diego Environmental Health   
17929        ' 2021-10-21 18:06:00                                        NRC   
17930        ' 2021-10-29 14:06:00                                    afdasdf   
17931        ' 2021-12-11 17:18:00                                       IBWC   
24727       '- 2020-05-22 15:14:00                              Southwest Gas   
24728        ' 2020-06-08 12:41:00                                      TEST    
24731        ' 2020-11-25 12:25:00                                        xxx   
24732        ' 2020-12-08 13:42:00                          Verisk 3E Company   
24733        ' 2020-12-09 16:09:00                                        NRC   
24734        ' 2020-12-18 20:52:00                                       NRC    
26643        ' 2019-10-01 09:30:00             Sacramento Area Sewer District   
32655        ' 2019-10-07 15:29:00                               So Cal Gas,    
32658        ' 2019-10-12 01:35:00                                       UPRR   
32659        ' 2019-11-12 12:38:00                              Whit O Briens   
32660        ' 2019-12-11 16:26:00                                        NRC   
64698        ' 2014-01-20 09:52:00                                        NRC   
79371        ' 2012-08-16 03:28:00                      City of Newport Beach   

                       1. Substance                        1. Quantity   
3450                         Sewage                            Unknown  \
5294            Unknown Oil (Sheen)  Length: 20  Feet / Width: 5  Feet   
17928                     Motor Oil                                 50   
17929  HYDRAULIC OIL(rainbow sheen)                        20FT x 15FT   
17930                        adfadf                                  2   
17931                        Sewage                              50000   
24727                   Natural Gas                            unknown   
24728                         TEST                                   3   
24731                           xxx                                 10   
24732             R507A Refrigerant                                175   
24733             Anhydrous Ammonia                                300   
24734                           NaN                            Unknown   
26643                        Sewage                               1100   
32655                   Natural Gas                            Unknown   
32658                        Diesel                            Unknown   
32659               Hydraulic Fluid                                  3   
32660               Transformer Oil                                 10   
64698                           Gas                                0.5   
79371                        Sewage                               2800   

      1. Measure    1. Type 1.  Other 1. Pipeline 1. Vessel >= 300 Tons   
3450     Unknown     SEWAGE       NaN          No                    No  \
5294       Sheen  PETROLEUM       NaN          No                    No   
17928     Gal(s)  PETROLEUM       NaN          No                    No   
17929      Sheen  PETROLEUM       NaN          No                    No   
17930     Gal(s)     SEWAGE       NaN          No                    No   
17931     Gal(s)     SEWAGE       NaN          No                    No   
24727        NaN      VAPOR       NaN          No                    No   
24728     Gal(s)  PETROLEUM       NaN          No                    No   
24731     Gal(s)  PETROLEUM       NaN          No                    No   
24732       Lbs.      VAPOR       NaN          No                    No   
24733       Lbs.      VAPOR       NaN          No                    No   
2473

### Clean rest of the data

Now, the blank_cases is clean. I am going to clean the rest of the data

In [27]:
hazmat_spills['Control#'].nunique()

102033

In [28]:
len(hazmat_spills)

102098

In [29]:
len(hazmat_spills) - hazmat_spills['Control#'].nunique()

65

In [30]:
hazmat_spills[hazmat_spills['Control#'].isna()]

Empty DataFrame
Columns: [Control#, Notified Date, Agency, 1. Substance, 1. Quantity, 1. Measure, 1. Type, 1.  Other, 1. Pipeline, 1. Vessel >= 300 Tons, 2. Substance, 2. Quantity, 2. Measure, 2. Type, 2.  Other, 2.  Pipeline, 2. Vessel >= 300 Tons, 3. Substance, 3. Quantity, 3. Measure, 3. Type, 3.  Other, 3.  Pipeline, 3.  Vessel >= 300 Tons, Description, Contained, Water?, Water Way, Location, City, County, Zip, Incident Date, Time, Spill Site, Site, CAUSE, CAUSE_Other, Injuries YES/NO, Injuries #, Fatals YES/NO, Fatals #, Evacs YES/NO, Evacs #, Cleanup, Admin Agency, DOG #, Notification Area, Drinking Water Impacted, Known Impact]
Index: []

There is no missing data, so 65 will be the number of duplicates

In [31]:
hazmat_spills[hazmat_spills['Control#'].duplicated()]

Control#       Notified Date   
2298   '23-1171 2023-02-14 14:39:00  \
4351   '22-6782 2022-11-17 12:58:00   
6452   '22-4522 2022-08-07 11:42:00   
6453   '22-4522 2022-08-07 11:42:00   
6454   '22-4522 2022-08-07 11:42:00   
...         ...                 ...   
74015  '13-2344 2013-04-19 10:34:00   
74016  '13-2344 2013-04-19 10:34:00   
79386  '12-0013 2012-05-29 16:17:00   
92861  '11-6022 2011-10-09 17:57:00   
96240  '10-1862 2010-03-18 05:02:00   

                                           Agency   
2298                          Sanmina Corporation  \
4351                 Lake County Special District   
6452    San Joaquin facilities management company   
6453    San Joaquin facilities management company   
6454    San Joaquin facilities management company   
...                                           ...   
74015  US Navy - Asst Safety Officer - USS Nimitz   
74016  US Navy - Asst Safety Officer - USS Nimitz   
79386                  Southern California Edison   
92861           Santa Clara Valley Water District   
96240                          US Navy Point Loma   

                        1. Substance          1. Quantity 1. Measure   
2298                      M-PREDIP L  2023-03-04 00:00:00     Gal(s)  \
4351                      Raw Sewage                   58     Gal(s)   
6452   Produced crude Oil (Non PCB)                     5    Bbl.(s)   
6453   Produced crude Oil (Non PCB)                     5    Bbl.(s)   
6454   Produced crude Oil (Non PCB)                     5    Bbl.(s)   
...                              ...                  ...        ...   
74015                         Grease                    1     Gal(s)   
74016                         Grease                    1     Gal(s)   
79386          Mineral Oil - Non PCB                    5     Gal(s)   
92861                         Sewage             5-10,000     Gal(s)   
96240                    Diesel Fuel                  400     Gal(s)   

              1. Type 1.  Other 1. Pipeline 1. Vessel >= 300 Tons   
2298   CHEMICAL,VAPOR       NaN          No                    No  \
4351           SEWAGE       NaN          No                    No   
6452        PETROLEUM       NaN          No                    No   
6453        PETROLEUM       NaN          No                    No   
6454        PETROLEUM       NaN          No                    No   
...               ...       ...         ...                   ...   
74015       PETROLEUM       NaN          No                    No   
74016       PETROLEUM       NaN          No                    No   
79386       PETROLEUM       NaN          No                    No   
92861          SEWAGE       NaN          No                    No   
96240       PETROLEUM       NaN         NaN                   NaN   

       2. Substance          2. Quantity 2. Measure         2. Type 2.  Other   
2298   CU Prep IV L  2023-03-04 00:00:00     Gal(s)  CHEMICAL,VAPOR       NaN  \
4351            NaN                  NaN        NaN             NaN       NaN   
6452            NaN                  NaN        NaN             NaN       NaN   
6453            NaN                  NaN        NaN             NaN       NaN   
6454            NaN                  NaN        NaN             NaN       NaN   
...             ...                  ...        ...             ...       ...   
74015           NaN                  NaN        NaN             NaN       NaN   
74016           NaN                  NaN        NaN             NaN       NaN   
79386           NaN                  NaN        NaN             NaN       NaN   
92861           NaN                  NaN        NaN             NaN       NaN   
96240           NaN                  NaN        NaN             NaN       NaN   

      2.  Pipeline 2. Vessel >= 300 Tons 3. Substance 3. Quantity 3. Measure   
2298            No                    No          NaN         NaN        NaN  \
4351            No                    No          NaN         NaN        N

In [32]:
hazmat_spills = hazmat_spills.drop_duplicates(subset=['Control#'])
hazmat_spills

Control#       Notified Date   
0       '23-3596 2023-06-01 13:30:00  \
1       '23-3595 2023-06-01 13:11:00   
2       '23-3594 2023-06-01 13:15:00   
3       '23-3592 2023-06-01 12:07:00   
4       '23-3591 2023-06-01 11:55:00   
...          ...                 ...   
102121  '10-7993 2010-12-31 13:20:00   
102122  '10-7994 2010-12-31 16:13:00   
102123  '10-7995 2010-12-31 17:13:00   
102124  '10-7996 2010-12-31 17:22:00   
102125  '10-7997 2010-12-31 18:20:00   

                                            Agency   
0                     Green Clean Pressure Washing  \
1                                             UPRR   
2                                    CHP - Barstow   
3                     California Northern Railroad   
4                                              NRC   
...                                            ...   
102121                                        CURA   
102122                                 Veeder Root   
102123  Victor Valley Waste Water Reclamation Auth   
102124                                Red Bluff FD   
102125                                         NRC   

                            1. Substance 1. Quantity 1. Measure    1. Type   
0                                Coolant           7     Gal(s)  PETROLEUM  \
1                            diesel fuel         100     Gal(s)  PETROLEUM   
2                      Corrosive Liquid           16       Lbs.   CHEMICAL   
3                            Bridge Fire           1        NaN      OTHER   
4                       Unknown Material     Unknown        NaN      VAPOR   
...                                  ...         ...        ...        ...   
102121                            Diesel          50     Gal(s)  PETROLEUM   
102122                          Gasoline           3     Gal(s)  PETROLEUM   
102123                      Sewage - Raw        3040     Gal(s)     SEWAGE   
102124  Oil - unk type, mixed with water          50     Gal(s)  PETROLEUM   
102125                       Unknown Oil     Unknown      Sheen  PETROLEUM   

                1.  Other 1. Pipeline 1. Vessel >= 300 Tons 2. Substance   
0                     NaN          No                    No          NaN  \
1                     NaN          No                    No          NaN   
2                     NaN          No                    No          NaN   
3                    Fire          No                    No          NaN   
4                     NaN          No                    No          NaN   
...                   ...         ...                   ...          ...   
102121                NaN         NaN                   NaN          NaN   
102122                NaN         NaN                   NaN          NaN   
102123                NaN         NaN                   NaN          NaN   
102124                NaN         NaN                   NaN          NaN   
102125  Faint diesel odor         NaN                   NaN          NaN   

       2. Quantity 2. Measure 2. Type 2.  Other 2.  Pipeline   
0              NaN        NaN     NaN       NaN           No  \
1              NaN        NaN     NaN       NaN           No   
2              NaN        NaN     NaN       NaN           No   
3              NaN        NaN     NaN       NaN           No   
4              NaN        NaN     NaN       NaN           No   
...            ...        ...     ...       ...          ...   
102121         NaN        NaN     NaN       NaN          NaN   
102122         NaN        NaN     NaN       NaN          NaN   
102123         NaN        NaN     NaN       NaN          NaN   
102124         NaN        NaN     NaN       NaN          NaN   
102125         NaN        NaN     NaN       NaN          NaN   

       2. Vessel >= 300 Tons 3. Substance 3. Quantity 3. Measure 3. Type   
0                         No          NaN         NaN        NaN     NaN  \
1                         No          NaN         NaN        NaN     NaN   
2                         No   

In [33]:
assert len(hazmat_spills) == hazmat_spills['Control#'].nunique()

Nice! Both of the blank_cases and hazmat_spills are cleaned. I need to merge them back.

### Merge the blank_cases and the rest of the data back to one dataframe

In [34]:
hazmat_spills_clean=pd.concat([hazmat_spills, blank_cases]).reset_index(drop=True) 

In [35]:
hazmat_spills_clean

Control#       Notified Date                        Agency   
0       '23-3596 2023-06-01 13:30:00  Green Clean Pressure Washing  \
1       '23-3595 2023-06-01 13:11:00                          UPRR   
2       '23-3594 2023-06-01 13:15:00                 CHP - Barstow   
3       '23-3592 2023-06-01 12:07:00  California Northern Railroad   
4       '23-3591 2023-06-01 11:55:00                           NRC   
...          ...                 ...                           ...   
102047         ' 2019-10-12 01:35:00                          UPRR   
102048         ' 2019-11-12 12:38:00                 Whit O Briens   
102049         ' 2019-12-11 16:26:00                           NRC   
102050         ' 2014-01-20 09:52:00                           NRC   
102051         ' 2012-08-16 03:28:00         City of Newport Beach   

             1. Substance 1. Quantity 1. Measure    1. Type 1.  Other   
0                 Coolant           7     Gal(s)  PETROLEUM       NaN  \
1             diesel fuel         100     Gal(s)  PETROLEUM       NaN   
2       Corrosive Liquid           16       Lbs.   CHEMICAL       NaN   
3             Bridge Fire           1        NaN      OTHER      Fire   
4        Unknown Material     Unknown        NaN      VAPOR       NaN   
...                   ...         ...        ...        ...       ...   
102047             Diesel     Unknown    Unknown  PETROLEUM       NaN   
102048    Hydraulic Fluid           3     Gal(s)  PETROLEUM       NaN   
102049    Transformer Oil          10     Gal(s)  PETROLEUM       NaN   
102050                Gas         0.5     Gal(s)  PETROLEUM       NaN   
102051             Sewage        2800     Gal(s)     SEWAGE       NaN   

       1. Pipeline 1. Vessel >= 300 Tons               2. Substance   
0               No                    No                        NaN  \
1               No                    No                        NaN   
2               No                    No                        NaN   
3               No                    No                        NaN   
4               No                    No                        NaN   
...            ...                   ...                        ...   
102047          No                    No                        NaN   
102048          No                    No                        NaN   
102049          No                    No  Polychlorinated Biphenyls   
102050          No                    No                        NaN   
102051          No                    No                        NaN   

       2. Quantity 2. Measure    2. Type 2.  Other 2.  Pipeline   
0              NaN        NaN        NaN       NaN           No  \
1              NaN        NaN        NaN       NaN           No   
2              NaN        NaN        NaN       NaN           No   
3              NaN        NaN        NaN       NaN           No   
4              NaN        NaN        NaN       NaN           No   
...            ...        ...        ...       ...          ...   
102047         NaN        NaN        NaN       NaN           No   
102048         NaN        NaN        NaN       NaN           No   
102049    Unknown     Unknown  PETROLEUM       NaN           No   
102050         NaN        NaN        NaN       NaN           No   
102051         NaN        NaN        NaN       NaN           No   

       2. Vessel >= 300 Tons 3. Substance 3. Quantity 3. Measure 3. Type   
0                         No          NaN         NaN        NaN     NaN  \
1                         No          NaN         NaN        NaN     NaN   
2                         No          NaN         NaN        NaN     NaN   
3                         No          NaN         NaN        NaN     NaN   
4                         No          NaN         NaN        NaN     NaN   
...                      ...          ...         ...        ...     ...   
102047                    No          NaN         NaN        NaN     NaN   
102048                  

## Drop unused columns

Since there are some columns with almost no entries in it or I will not use them for the analysis, I am going to drop them. 

In [36]:
columns_to_drop = ['1. Pipeline', '1. Vessel >= 300 Tons', '1. Substance', '1.  Other', '1. Quantity', '1. Measure', 'Contained', 'Water?', 'Water Way', '2. Substance', '2. Quantity', '2. Measure', '2. Type', '2.  Other', '2.  Pipeline', '2. Vessel >= 300 Tons', '3. Substance', '3. Quantity', '3. Measure', '3. Type', '3.  Other', '3.  Pipeline', '3.  Vessel >= 300 Tons', 'DOG #', 'Cleanup', 'Admin Agency', 'Notification Area']

In [37]:
hazmat_spills_clean=hazmat_spills_clean.drop(columns=columns_to_drop, axis=1)

In [38]:
hazmat_spills_clean

Control#       Notified Date                        Agency    1. Type   
0       '23-3596 2023-06-01 13:30:00  Green Clean Pressure Washing  PETROLEUM  \
1       '23-3595 2023-06-01 13:11:00                          UPRR  PETROLEUM   
2       '23-3594 2023-06-01 13:15:00                 CHP - Barstow   CHEMICAL   
3       '23-3592 2023-06-01 12:07:00  California Northern Railroad      OTHER   
4       '23-3591 2023-06-01 11:55:00                           NRC      VAPOR   
...          ...                 ...                           ...        ...   
102047         ' 2019-10-12 01:35:00                          UPRR  PETROLEUM   
102048         ' 2019-11-12 12:38:00                 Whit O Briens  PETROLEUM   
102049         ' 2019-12-11 16:26:00                           NRC  PETROLEUM   
102050         ' 2014-01-20 09:52:00                           NRC  PETROLEUM   
102051         ' 2012-08-16 03:28:00         City of Newport Beach     SEWAGE   

                                              Description   
0       RP stated that a waste management truck experi...  \
1       RP States: Locomotive released fuel onto the t...   
2       RP stated that a semi trucks breaks caught on ...   
3       RP states: A bridge by MP 174.8 of the westval...   
4       Per NRC: "THE CALLER STATES UNKNOWN CHEMICALS ...   
...                                                   ...   
102047  conductorsCaller states a locomotive was leaki...   
102048  RP states: While Piledriving a hydraulic hose ...   
102049  Per NRC Report: "CALLER REPORTING THAT THE DOW...   
102050  Per NRC#1071643 "DISPENSER #9 SPILLED ROUGHLY ...   
102051  RP states that a dredging company hit a sewer ...   

                                       Location           City   
0                                3835 Kern Road          Chino  \
1                          Near Main St, MP 156     Dutch Flat   
2                      Lynwood Road Offramp I15        Lynwood   
3       MP 174.8 of the westvalley sub division        Corning   
4                       15617 S. WHITE AVENUE          Compton   
...                                         ...            ...   
102047              Roseville, CA to Sparks, NV      Roseville   
102048                       1374 Pier F Avenue     Long Beach   
102049        Boardmoor Dr. and Bellemeade Dr.       San Ramon   
102050                           1804 W 11TH ST          Tracy   
102051                          1701 Bayside Dr  Newport Beach   

                       County    Zip        Incident Date     Time   
0       San Bernardino County    NaN  2023-05-31 00:00:00     1700  \
1               Placer County    NaN  2023-06-01 00:00:00  1350 CT   
2          Los Angeles County    NaN  2023-05-31 00:00:00     2306   
3               Tehama County    NaN  2023-06-01 00:00:00     1715   
4          Los Angeles County    NaN           06/01/0023     1400   
...                       ...    ...                  ...      ...   
102047          Placer County    NaN  2019-10-11 00:00:00     2021   
102048     Los Angeles County    NaN  2019-11-12 00:00:00     1145   
102049    Contra Costa County    NaN                  NaN      NaN   
102050     San Joaquin County  95376  2014-01-20 00:00:00      915   
102051          Orange County    NaN  2012-08-15 00:00:00     2300   

               Spill Site               Site        CAUSE CAUSE_Other   
0                    Road                NaN   Mechanical         NaN  \
1               Rail Road                NaN      Unknown         NaN   
2                    Road                NaN      Unknown         NaN   
3                    Road                NaN      Unknown         NaN   
4               Residence                NaN      Unknown         NaN   
...                   ...                ...          ...         ...   
102047          Rail Road            Unknown   Mechanical         NaN   
102048          Waterways  Port of Longbeach   Mechanical         NaN   
102049     

## Convert Time

In [39]:
hazmat_spills_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102052 entries, 0 to 102051
Data columns (total 23 columns):
 #   Column                   Non-Null Count   Dtype         
---  ------                   --------------   -----         
 0   Control#                 102052 non-null  object        
 1   Notified Date            102052 non-null  datetime64[ns]
 2   Agency                   101976 non-null  object        
 3   1. Type                  102052 non-null  object        
 4   Description              102049 non-null  object        
 5   Location                 102042 non-null  object        
 6   City                     102032 non-null  object        
 7   County                   102025 non-null  object        
 8   Zip                      54755 non-null   object        
 9   Incident Date            102046 non-null  object        
 10  Time                     102034 non-null  object        
 11  Spill Site               102046 non-null  object        
 12  Site            

By checking the info, I noticed there are three time-related columns: Notified Date, Incident Date and Time. However, only Notified Date has been changed to datatime automatically. So, I will convert the other two.

### Formatting the time column

In [40]:
hazmat_spills_clean['Time']

0            1700
1         1350 CT
2            2306
3            1715
4            1400
           ...   
102047       2021
102048       1145
102049        NaN
102050        915
102051       2300
Name: Time, Length: 102052, dtype: object

The time in the column is not actually in a %H:%M format, so I need to address that. Before doing that, I will check if there are any NaN rows.

#### Drop NaN rows

In [41]:
hazmat_spills_clean[hazmat_spills_clean['Time'].isna()]

Control#       Notified Date                          Agency   
3501    '22-7683 2022-12-31 14:17:00  Sewer Authority Mid Coast Side  \
3502    '22-7682 2022-12-31 14:15:00  Sewer Authority Mid Coast Side   
3506    '22-7678 2022-12-31 14:12:00  Sewer Authority Mid Coast Side   
3507    '22-7677 2022-12-31 14:09:00  Sewer Authority Mid Coast Side   
3509    '22-7675 2022-12-31 14:06:00  Sewer Authority Mid Coast Side   
3510    '22-7674 2022-12-31 13:57:00   Sewer Authority MidCoast Side   
30554   '19-2128 2019-03-31 08:32:00                             NRC   
30847   '19-1814 2019-03-15 15:31:00                             NRC   
44545   '17-5469 2017-08-02 08:45:00                       Anonymous   
44547   '17-5467 2017-08-02 08:21:00                       Anonymous   
57064   '16-0256 2016-01-12 17:40:00       San Luis Obispo City Fire   
59662   '15-2440 2015-05-01 11:14:00                            CDFA   
81689   '12-2462 2012-04-25 09:27:00                             NRC   
93119   '11-6387 2011-10-26 11:56:00                      Hazmat One   
102038         ' 2021-12-11 17:18:00                            IBWC   
102044         ' 2020-12-18 20:52:00                            NRC    
102046         ' 2019-10-07 15:29:00                    So Cal Gas,    
102049         ' 2019-12-11 16:26:00                             NRC   

                       1. Type   
3501                    SEWAGE  \
3502                    SEWAGE   
3506                    SEWAGE   
3507                    SEWAGE   
3509                    SEWAGE   
3510                    SEWAGE   
30554                PETROLEUM   
30847      RAILROAD DERAILMENT   
44545                 CHEMICAL   
44547                 CHEMICAL   
57064    cleanup was completed   
59662                  Unknown   
81689              storm drain   
93119                       No   
102038                  SEWAGE   
102044                   VAPOR   
102046                   VAPOR   
102049               PETROLEUM   

                                              Description   
3501    Reporting party states due to the storm a manh...  \
3502    Reporting party states due to the storm a manh...   
3506     Reporting party states due to the storm a man...   
3507    Reporting party states due to the storm a manh...   
3509     Reporting party states due to the storm a man...   
3510    Reporting party states due to the storm a manh...   
30554   Per the NRC, "CALLER REPORTED AN UNKNOWN SHEEN...   
30847   Per the NRC, "CALLER REPORTS THAT TRAIN CALLED...   
44545   ***POTENTIAL RELEASE***  Caller states illegal...   
44547   Caller states illegal marijuana grow on privat...   
57064                                                 NaN   
59662                                     Reporting Party   
81689                              Downey Fire Department   
93119                                   Responsible Party   
102038  Per caller, due to an unknown reason there is ...   
102044                                                NaN   
102046                                                NaN   
102049  Per NRC Report: "CALLER REPORTING THAT THE DOW...   

                                                 Location   
3501                               37.519998 - 122.511331  \
3502                               37.523989 - 122.510697   
3506                               37.534262 - 122.518903   
3507                               37.495873 - 122.462182   
3509                               37.501345 - 122.471788   
3510        37.501620 - 122.471444, 37.501660 - 122471547   
30554                                                 NaN   
30847   "STEWART MESA FACILITY YARD " // MP 222.55 in ...   
44545                                      4220 Tree Lane   
44547                      4477 Lynn Blvd, 4499 Lynn Blvd   
57064                San Luis Obispo City Fire Department   
59662                                                 NaN   
81689                                  

In [42]:
hazmat_spills_clean.dropna(subset=['Time'], inplace=True)

In [43]:
hazmat_spills_clean

Control#       Notified Date                          Agency   
0       '23-3596 2023-06-01 13:30:00    Green Clean Pressure Washing  \
1       '23-3595 2023-06-01 13:11:00                            UPRR   
2       '23-3594 2023-06-01 13:15:00                   CHP - Barstow   
3       '23-3592 2023-06-01 12:07:00    California Northern Railroad   
4       '23-3591 2023-06-01 11:55:00                             NRC   
...          ...                 ...                             ...   
102045         ' 2019-10-01 09:30:00  Sacramento Area Sewer District   
102047         ' 2019-10-12 01:35:00                            UPRR   
102048         ' 2019-11-12 12:38:00                   Whit O Briens   
102050         ' 2014-01-20 09:52:00                             NRC   
102051         ' 2012-08-16 03:28:00           City of Newport Beach   

          1. Type                                        Description   
0       PETROLEUM  RP stated that a waste management truck experi...  \
1       PETROLEUM  RP States: Locomotive released fuel onto the t...   
2        CHEMICAL  RP stated that a semi trucks breaks caught on ...   
3           OTHER  RP states: A bridge by MP 174.8 of the westval...   
4           VAPOR  Per NRC: "THE CALLER STATES UNKNOWN CHEMICALS ...   
...           ...                                                ...   
102045     SEWAGE  RP advised that there was a blockage in the lo...   
102047  PETROLEUM  conductorsCaller states a locomotive was leaki...   
102048  PETROLEUM  RP states: While Piledriving a hydraulic hose ...   
102050  PETROLEUM  Per NRC#1071643 "DISPENSER #9 SPILLED ROUGHLY ...   
102051     SEWAGE  RP states that a dredging company hit a sewer ...   

                                       Location           City   
0                                3835 Kern Road          Chino  \
1                          Near Main St, MP 156     Dutch Flat   
2                      Lynwood Road Offramp I15        Lynwood   
3       MP 174.8 of the westvalley sub division        Corning   
4                       15617 S. WHITE AVENUE          Compton   
...                                         ...            ...   
102045                        9801 Beachwood Dr     Orangevale   
102047              Roseville, CA to Sparks, NV      Roseville   
102048                       1374 Pier F Avenue     Long Beach   
102050                           1804 W 11TH ST          Tracy   
102051                          1701 Bayside Dr  Newport Beach   

                       County    Zip        Incident Date     Time   
0       San Bernardino County    NaN  2023-05-31 00:00:00     1700  \
1               Placer County    NaN  2023-06-01 00:00:00  1350 CT   
2          Los Angeles County    NaN  2023-05-31 00:00:00     2306   
3               Tehama County    NaN  2023-06-01 00:00:00     1715   
4          Los Angeles County    NaN           06/01/0023     1400   
...                       ...    ...                  ...      ...   
102045      Sacramento County  95662  2019-09-03 00:00:00      831   
102047          Placer County    NaN  2019-10-11 00:00:00     2021   
102048     Los Angeles County    NaN  2019-11-12 00:00:00     1145   
102050     San Joaquin County  95376  2014-01-20 00:00:00      915   
102051          Orange County    NaN  2012-08-15 00:00:00     2300   

               Spill Site               Site        CAUSE CAUSE_Other   
0                    Road                NaN   Mechanical         NaN  \
1               Rail Road                NaN      Unknown         NaN   
2                    Road                NaN      Unknown         NaN   
3                    Road                NaN      Unknown         NaN   
4               Residence                NaN      Unknown         NaN   
...                   ...                ...          ...         ...   
102045          Residence        Storm Drain     Blockage         NaN   
102047          Rail Road            Unknown   Mechanical   

In [44]:
hazmat_spills_clean.reset_index(drop=True)

Control#       Notified Date                          Agency   
0       '23-3596 2023-06-01 13:30:00    Green Clean Pressure Washing  \
1       '23-3595 2023-06-01 13:11:00                            UPRR   
2       '23-3594 2023-06-01 13:15:00                   CHP - Barstow   
3       '23-3592 2023-06-01 12:07:00    California Northern Railroad   
4       '23-3591 2023-06-01 11:55:00                             NRC   
...          ...                 ...                             ...   
102029         ' 2019-10-01 09:30:00  Sacramento Area Sewer District   
102030         ' 2019-10-12 01:35:00                            UPRR   
102031         ' 2019-11-12 12:38:00                   Whit O Briens   
102032         ' 2014-01-20 09:52:00                             NRC   
102033         ' 2012-08-16 03:28:00           City of Newport Beach   

          1. Type                                        Description   
0       PETROLEUM  RP stated that a waste management truck experi...  \
1       PETROLEUM  RP States: Locomotive released fuel onto the t...   
2        CHEMICAL  RP stated that a semi trucks breaks caught on ...   
3           OTHER  RP states: A bridge by MP 174.8 of the westval...   
4           VAPOR  Per NRC: "THE CALLER STATES UNKNOWN CHEMICALS ...   
...           ...                                                ...   
102029     SEWAGE  RP advised that there was a blockage in the lo...   
102030  PETROLEUM  conductorsCaller states a locomotive was leaki...   
102031  PETROLEUM  RP states: While Piledriving a hydraulic hose ...   
102032  PETROLEUM  Per NRC#1071643 "DISPENSER #9 SPILLED ROUGHLY ...   
102033     SEWAGE  RP states that a dredging company hit a sewer ...   

                                       Location           City   
0                                3835 Kern Road          Chino  \
1                          Near Main St, MP 156     Dutch Flat   
2                      Lynwood Road Offramp I15        Lynwood   
3       MP 174.8 of the westvalley sub division        Corning   
4                       15617 S. WHITE AVENUE          Compton   
...                                         ...            ...   
102029                        9801 Beachwood Dr     Orangevale   
102030              Roseville, CA to Sparks, NV      Roseville   
102031                       1374 Pier F Avenue     Long Beach   
102032                           1804 W 11TH ST          Tracy   
102033                          1701 Bayside Dr  Newport Beach   

                       County    Zip        Incident Date     Time   
0       San Bernardino County    NaN  2023-05-31 00:00:00     1700  \
1               Placer County    NaN  2023-06-01 00:00:00  1350 CT   
2          Los Angeles County    NaN  2023-05-31 00:00:00     2306   
3               Tehama County    NaN  2023-06-01 00:00:00     1715   
4          Los Angeles County    NaN           06/01/0023     1400   
...                       ...    ...                  ...      ...   
102029      Sacramento County  95662  2019-09-03 00:00:00      831   
102030          Placer County    NaN  2019-10-11 00:00:00     2021   
102031     Los Angeles County    NaN  2019-11-12 00:00:00     1145   
102032     San Joaquin County  95376  2014-01-20 00:00:00      915   
102033          Orange County    NaN  2012-08-15 00:00:00     2300   

               Spill Site               Site        CAUSE CAUSE_Other   
0                    Road                NaN   Mechanical         NaN  \
1               Rail Road                NaN      Unknown         NaN   
2                    Road                NaN      Unknown         NaN   
3                    Road                NaN      Unknown         NaN   
4               Residence                NaN      Unknown         NaN   
...                   ...                ...          ...         ...   
102029          Residence        Storm Drain     Blockage         NaN   
102030          Rail Road            Unknown   Mechanical   

#### Drop rows with text

In [45]:
# convert time to string
hazmat_spills_clean['Time'] = hazmat_spills_clean['Time'].astype(str)

In [46]:
hazmat_spills_clean['Time'].str[-2:]

0         00
1         CT
2         06
3         15
4         00
          ..
102045    31
102047    21
102048    45
102050    15
102051    00
Name: Time, Length: 102034, dtype: object

Some of rows have time zone mark, I need to clean up them. To do so, I will look at the rows that contain space

In [47]:
hazmat_spills_clean[
    hazmat_spills_clean['Time'].str.contains(' ')
]

Control#       Notified Date                      Agency      1. Type   
1       '23-3595 2023-06-01 13:11:00                        UPRR    PETROLEUM  \
120     '23-3462 2023-05-25 12:38:00               Union Pacific    PETROLEUM   
304     '23-3266 2023-05-18 09:49:00                         NaN     CHEMICAL   
1467    '23-2034 2023-03-19 10:51:00                         NRC  UNSPECIFIED   
1892    '23-1591 2023-03-06 12:03:00      Union Pacific Railroad     RAILROAD   
...          ...                 ...                         ...          ...   
71384   '14-7178 2014-12-15 08:22:00           Molycorp Minerals     CHEMICAL   
77077   '13-5611 2013-09-07 09:53:00  Southern California Edison    PETROLEUM   
78134   '13-6717 2013-10-29 18:02:00                        PG&E    PETROLEUM   
95876   '10-1578 2010-03-05 09:36:00                         NRC    PETROLEUM   
101440  '10-7371 2010-12-08 11:43:00                      CHP-LA    PETROLEUM   

                                              Description   
1       RP States: Locomotive released fuel onto the t...  \
120     RP States: They received a call reporting dies...   
304     Caller believes a deceased male buried multipl...   
1467    ***Potential Release***  NRC: Caller stated th...   
1892    RP States: Freight train YLA51 of the 6th, tra...   
...                                                   ...   
71384   Caller states the scrubber system overflowed t...   
77077   Caller states:  A 1973 pole top overhead trans...   
78134   Caller states equipment failure on a pole-moun...   
95876   Per NRC Report, "caller reported a sinking ves...   
101440                     Release due mechanical failure   

                           Location           City                 County   
1              Near Main St, MP 156     Dutch Flat          Placer County  \
120             19100 Slover Avenue    Bloomington  San Bernardino County   
304     11223 & 11211 Kadota Avenue         Pomona     Los Angeles County   
1467            2920 E. Cliff Drive     Santa Cruz      Santa Cruz County   
1892    MP 3.4 of the San Pedro Sub         Vernon     Los Angeles County   
...                             ...            ...                    ...   
71384             67750 Bailey Road  Mountain Pass  San Bernardino County   
77077            Amboy Rd. x Tetra           Amboy  San Bernardino County   
78134      510 South Chester Avenue    Bakersfield            Kern County   
95876            550 Marina Parkway    Chula Vista       San Diego County   
101440  W/B 91just east of Santa Fe        Compton     Los Angeles County   

          Zip        Incident Date                 Time        Spill Site   
1         NaN  2023-06-01 00:00:00              1350 CT         Rail Road  \
120       NaN  2023-05-25 00:00:00               227 CT         Rail Road   
304     91766  2023-05-18 00:00:00  2023-09-18 00:00:00             Other   
1467      NaN  2023-03-19 00:00:00  2920 E. Cliff Drive         Waterways   
1892      NaN  2023-03-06 00:00:00         1349 Central         Rail Road   
...       ...                  ...                  ...               ...   
71384   92366  2014-12-14 00:00:00           0130 -1215             Other   
77077     NaN  2013-09-07 00:00:00  2015-09-19 00:00:00             Other   
78134     NaN  2300-10-01 00:00:00  2013-10-28 00:00:00         Residence   
95876   91910  2010-03-05 00:00:00  2010-03-05 00:00:00  Ship/Harbor/Port   
101440    NaN  2010-12-08 00:00:00  2010-12-08 00:00:00              Road   

                             Site       CAUSE              CAUSE_Other   
1                             NaN     Unknown                      NaN  \
120                           NaN     Unknown                      NaN   
304                           NaN     Unknown                      NaN   
1467                Pacific Ocean     Unknown                      NaN   
1892                          NaN   Collision                      NaN   
...     

There are at least 343 rows of data in which the `Time` column has a space in it. There are quite a lot of them are actually not a time. I choose split these out and not use them for the analysis

In [48]:
hazmat_spills_clean = hazmat_spills_clean[
    ~hazmat_spills_clean['Time'].str.contains(' ')
]
hazmat_spills_clean

Control#       Notified Date                          Agency   
0       '23-3596 2023-06-01 13:30:00    Green Clean Pressure Washing  \
2       '23-3594 2023-06-01 13:15:00                   CHP - Barstow   
3       '23-3592 2023-06-01 12:07:00    California Northern Railroad   
4       '23-3591 2023-06-01 11:55:00                             NRC   
5       '23-3590 2023-06-01 11:32:00                             NRC   
...          ...                 ...                             ...   
102045         ' 2019-10-01 09:30:00  Sacramento Area Sewer District   
102047         ' 2019-10-12 01:35:00                            UPRR   
102048         ' 2019-11-12 12:38:00                   Whit O Briens   
102050         ' 2014-01-20 09:52:00                             NRC   
102051         ' 2012-08-16 03:28:00           City of Newport Beach   

          1. Type                                        Description   
0       PETROLEUM  RP stated that a waste management truck experi...  \
2        CHEMICAL  RP stated that a semi trucks breaks caught on ...   
3           OTHER  RP states: A bridge by MP 174.8 of the westval...   
4           VAPOR  Per NRC: "THE CALLER STATES UNKNOWN CHEMICALS ...   
5       PETROLEUM  Per NRC: "CALLER STATED THAT THREE 55 GALLON D...   
...           ...                                                ...   
102045     SEWAGE  RP advised that there was a blockage in the lo...   
102047  PETROLEUM  conductorsCaller states a locomotive was leaki...   
102048  PETROLEUM  RP states: While Piledriving a hydraulic hose ...   
102050  PETROLEUM  Per NRC#1071643 "DISPENSER #9 SPILLED ROUGHLY ...   
102051     SEWAGE  RP states that a dredging company hit a sewer ...   

                                       Location           City   
0                                3835 Kern Road          Chino  \
2                      Lynwood Road Offramp I15        Lynwood   
3       MP 174.8 of the westvalley sub division        Corning   
4                       15617 S. WHITE AVENUE          Compton   
5                                 Off of SR 118          Somis   
...                                         ...            ...   
102045                        9801 Beachwood Dr     Orangevale   
102047              Roseville, CA to Sparks, NV      Roseville   
102048                       1374 Pier F Avenue     Long Beach   
102050                           1804 W 11TH ST          Tracy   
102051                          1701 Bayside Dr  Newport Beach   

                       County    Zip        Incident Date  Time   
0       San Bernardino County    NaN  2023-05-31 00:00:00  1700  \
2          Los Angeles County    NaN  2023-05-31 00:00:00  2306   
3               Tehama County    NaN  2023-06-01 00:00:00  1715   
4          Los Angeles County    NaN           06/01/0023  1400   
5              Ventura County    NaN  2023-06-01 00:00:00   945   
...                       ...    ...                  ...   ...   
102045      Sacramento County  95662  2019-09-03 00:00:00   831   
102047          Placer County    NaN  2019-10-11 00:00:00  2021   
102048     Los Angeles County    NaN  2019-11-12 00:00:00  1145   
102050     San Joaquin County  95376  2014-01-20 00:00:00   915   
102051          Orange County    NaN  2012-08-15 00:00:00  2300   

               Spill Site               Site        CAUSE CAUSE_Other   
0                    Road                NaN   Mechanical         NaN  \
2                    Road                NaN      Unknown         NaN   
3                    Road                NaN      Unknown         NaN   
4               Residence                NaN      Unknown         NaN   
5               Waterways  Santa Clara River        Other     Dumping   
...                   ...                ...          ...         ...   
102045          Residence        Storm Drain     Blockage         NaN   
102047          Rail Road            Unknown   Mechanical         NaN   
102048          Waterwa

In [49]:
hazmat_spills_clean.reset_index(drop=True)

Control#       Notified Date                          Agency   
0       '23-3596 2023-06-01 13:30:00    Green Clean Pressure Washing  \
1       '23-3594 2023-06-01 13:15:00                   CHP - Barstow   
2       '23-3592 2023-06-01 12:07:00    California Northern Railroad   
3       '23-3591 2023-06-01 11:55:00                             NRC   
4       '23-3590 2023-06-01 11:32:00                             NRC   
...          ...                 ...                             ...   
101686         ' 2019-10-01 09:30:00  Sacramento Area Sewer District   
101687         ' 2019-10-12 01:35:00                            UPRR   
101688         ' 2019-11-12 12:38:00                   Whit O Briens   
101689         ' 2014-01-20 09:52:00                             NRC   
101690         ' 2012-08-16 03:28:00           City of Newport Beach   

          1. Type                                        Description   
0       PETROLEUM  RP stated that a waste management truck experi...  \
1        CHEMICAL  RP stated that a semi trucks breaks caught on ...   
2           OTHER  RP states: A bridge by MP 174.8 of the westval...   
3           VAPOR  Per NRC: "THE CALLER STATES UNKNOWN CHEMICALS ...   
4       PETROLEUM  Per NRC: "CALLER STATED THAT THREE 55 GALLON D...   
...           ...                                                ...   
101686     SEWAGE  RP advised that there was a blockage in the lo...   
101687  PETROLEUM  conductorsCaller states a locomotive was leaki...   
101688  PETROLEUM  RP states: While Piledriving a hydraulic hose ...   
101689  PETROLEUM  Per NRC#1071643 "DISPENSER #9 SPILLED ROUGHLY ...   
101690     SEWAGE  RP states that a dredging company hit a sewer ...   

                                       Location           City   
0                                3835 Kern Road          Chino  \
1                      Lynwood Road Offramp I15        Lynwood   
2       MP 174.8 of the westvalley sub division        Corning   
3                       15617 S. WHITE AVENUE          Compton   
4                                 Off of SR 118          Somis   
...                                         ...            ...   
101686                        9801 Beachwood Dr     Orangevale   
101687              Roseville, CA to Sparks, NV      Roseville   
101688                       1374 Pier F Avenue     Long Beach   
101689                           1804 W 11TH ST          Tracy   
101690                          1701 Bayside Dr  Newport Beach   

                       County    Zip        Incident Date  Time   
0       San Bernardino County    NaN  2023-05-31 00:00:00  1700  \
1          Los Angeles County    NaN  2023-05-31 00:00:00  2306   
2               Tehama County    NaN  2023-06-01 00:00:00  1715   
3          Los Angeles County    NaN           06/01/0023  1400   
4              Ventura County    NaN  2023-06-01 00:00:00   945   
...                       ...    ...                  ...   ...   
101686      Sacramento County  95662  2019-09-03 00:00:00   831   
101687          Placer County    NaN  2019-10-11 00:00:00  2021   
101688     Los Angeles County    NaN  2019-11-12 00:00:00  1145   
101689     San Joaquin County  95376  2014-01-20 00:00:00   915   
101690          Orange County    NaN  2012-08-15 00:00:00  2300   

               Spill Site               Site        CAUSE CAUSE_Other   
0                    Road                NaN   Mechanical         NaN  \
1                    Road                NaN      Unknown         NaN   
2                    Road                NaN      Unknown         NaN   
3               Residence                NaN      Unknown         NaN   
4               Waterways  Santa Clara River        Other     Dumping   
...                   ...                ...          ...         ...   
101686          Residence        Storm Drain     Blockage         NaN   
101687          Rail Road            Unknown   Mechanical         NaN   
101688          Waterwa

Now, I got all the columns with the time that are ready to be converted

#### Convert to the time format

In [50]:
hazmat_spills_clean['Time']

0         1700
2         2306
3         1715
4         1400
5          945
          ... 
102045     831
102047    2021
102048    1145
102050     915
102051    2300
Name: Time, Length: 101691, dtype: object

In [51]:
hazmat_spills_clean['Hour'] = hazmat_spills_clean['Time'].str[0:-2]

/var/folders/s1/34kl6rwj7nx2q7mpwcv0yq1w0000gn/T/ipykernel_93301/750131113.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hazmat_spills_clean['Hour'] = hazmat_spills_clean['Time'].str[0:-2]


As I got this warning, I asked Chatgpt how to resolve it.

Chatgpt: The warning you are encountering is a pandas SettingWithCopyWarning. This warning is issued to inform you that you are attempting to modify a DataFrame that might be a view on another DataFrame instead of the actual DataFrame you intended to modify. This situation can lead to unexpected behavior.

To avoid this warning and ensure that you are modifying the original DataFrame, you can use the .loc accessor.

I will do what Chatgpt told me to do:

In [52]:
hazmat_spills_clean.loc[:, 'Hour'] = hazmat_spills_clean['Time'].str[0:-2]


Chatgpt told me that "The [:, ...] syntax in the context of hazmat_spills_clean.loc[:, 'Hour'] is using the .loc accessor with two parameters: the row indexer (:) and the column indexer ('Hour'). The colon (:) is used to select all rows."

In [53]:
hazmat_spills_clean['Hour']

0         17
2         23
3         17
4         14
5          9
          ..
102045     8
102047    20
102048    11
102050     9
102051    23
Name: Hour, Length: 101691, dtype: object

In [54]:
hazmat_spills_clean.loc[:, 'Minutes'] = hazmat_spills_clean['Time'].str[-2:]

/var/folders/s1/34kl6rwj7nx2q7mpwcv0yq1w0000gn/T/ipykernel_93301/2677372248.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hazmat_spills_clean.loc[:, 'Minutes'] = hazmat_spills_clean['Time'].str[-2:]


In [55]:
hazmat_spills_clean['Minutes']

0         00
2         06
3         15
4         00
5         45
          ..
102045    31
102047    21
102048    45
102050    15
102051    00
Name: Minutes, Length: 101691, dtype: object

In [56]:
hazmat_spills_clean.loc[:, 'Time_Cleaned'] = hazmat_spills_clean['Hour'] + ':' + hazmat_spills_clean['Minutes']

/var/folders/s1/34kl6rwj7nx2q7mpwcv0yq1w0000gn/T/ipykernel_93301/1270344606.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hazmat_spills_clean.loc[:, 'Time_Cleaned'] = hazmat_spills_clean['Hour'] + ':' + hazmat_spills_clean['Minutes']


In [57]:
hazmat_spills_clean['Time_Cleaned'] 

0         17:00
2         23:06
3         17:15
4         14:00
5          9:45
          ...  
102045     8:31
102047    20:21
102048    11:45
102050     9:15
102051    23:00
Name: Time_Cleaned, Length: 101691, dtype: object

Now I have the right format of time!

### Formatting the Incident Date Column

In [58]:
hazmat_spills_clean.loc[:, 'Incident Date'] = hazmat_spills_clean['Incident Date'].astype(str)

In [59]:
hazmat_spills_clean['Incident Date']

0         2023-05-31 00:00:00
2         2023-05-31 00:00:00
3         2023-06-01 00:00:00
4                  06/01/0023
5         2023-06-01 00:00:00
                 ...         
102045    2019-09-03 00:00:00
102047    2019-10-11 00:00:00
102048    2019-11-12 00:00:00
102050    2014-01-20 00:00:00
102051    2012-08-15 00:00:00
Name: Incident Date, Length: 101691, dtype: object

I noticed that some of the data in this columns have typo (e.g., in row 4, there is 0023), I need to address them first. I also noticed that when I imported data, the timestamps are given automatically, which add a space between the date and the timestamp. So to check the columns that have typo, I just need to find columns not contain a space

#### Drop rows with typo

In [60]:
hazmat_spills_clean[
    ~hazmat_spills_clean['Incident Date'].str.contains(' ')
]

Control#       Notified Date              Agency      1. Type   
4       '23-3591 2023-06-01 11:55:00                 NRC        VAPOR  \
390     '23-3174 2023-05-13 15:49:00          Anonymous         OTHER   
900     '23-2645 2023-04-15 12:32:00  City of San Diego        SEWAGE   
1025    '23-2511 2023-04-09 10:45:00      Southwest Gas         VAPOR   
1163    '23-2367 2023-03-31 17:30:00   Cal Fire Mariposa    PETROLEUM   
...          ...                 ...                 ...          ...   
99101   '10-4918 2010-08-17 09:55:00   Lassen County OES    PETROLEUM   
99627   '10-5459 2010-09-10 13:31:00   Sherwood Williams     CHEMICAL   
101135  '10-7043 2010-11-23 07:50:00        East Bay MUD       SEWAGE   
101648  '10-7607 2010-12-19 06:14:00    City of Richmond       SEWAGE   
101931  '10-7892 2010-12-27 16:02:00                 NRC  UNSPECIFIED   

                                              Description   
4       Per NRC: "THE CALLER STATES UNKNOWN CHEMICALS ...  \
390     Caller stated that due to a fire there is an u...   
900     Due to heavy root blockage there was a release...   
1025    Caller states snow and ice broke a regulator a...   
1163    Big rig involved in a MVA with another unknown...   
...                                                   ...   
99101   A logging truck hit a rock which tore up his o...   
99627              A painter spilled it onto a side walk.   
101135  The caller is reporting a discharge from their...   
101648  Caller states that due to the storm surge a de...   
101931  CALLER SUSPECTS THAT AN INDIVIDUAL IS RUNNING ...   

                                              Location              City   
4                              15617 S. WHITE AVENUE             Compton  \
390                               Fox Drive / Aspen Dr    Springville(1)   
900                                    7758 Via Capri          San Diego   
1025                                   2176 Chiapa Dr   South Lake Tahoe   
1163               North Scaffer Road x Eucalyptus Ave            Winton   
...                                                ...               ...   
99101                      461-445 Whispering Pines Rd        Janesville   
99627                                 8311 Haskell Ave         Sepulveda   
101135  Oakport Wet Weather facility, 5597 Oakport St.           Oakland   
101648                            860 Harbor Way South          Richmond   
101931                              3021 Riverview Way         Hollister   

                     County    Zip Incident Date  Time   
4        Los Angeles County    NaN    06/01/0023  1400  \
390           Tulare County    NaN    05/13/0023  1145   
900        San Diego County    NaN    04/01/1523  1100   
1025       El Dorado County  96150    04/01/1047   958   
1163          Merced County    NaN    03/31/0223  1645   
...                     ...    ...           ...   ...   
99101           Lake County  96114    08/16/0201  1814   
99627    Los Angeles County    NaN    09/03/0201   900   
101135       Alameda County  94601    10/01/1120  2048   
101648  Contra Costa County    NaN    10/19/0112   600   
101931    San Benito County  95203    12/10/0227  1510   

                       Spill Site               Site        CAUSE   
4                       Residence                NaN      Unknown  \
390                     Waterways       Holby Creek         Other   
900                          Road                NaN     Blockage   
1025                    Residence                NaN        Other   
1163                    Residence                NaN      Unknown   
...                           ...                ...          ...   
99101                        Road                NaN    Collision   
99627                       Other                NaN  Human Error   
101135  Treatment/Sewage Facility  San Francisco Bay        Other   
101648  Treatment/Sewage Facility   Sante Fe Channel        Other   
101931                  Resid

There are not many of them and some of the rows are probably entered wrong (e.g., row 1025) that I cannot identify the year. I will just get rid of all of them.

In [61]:
hazmat_spills_clean=hazmat_spills_clean[
    hazmat_spills_clean['Incident Date'].str.contains(' ')
]

In [62]:
hazmat_spills_clean

Control#       Notified Date                          Agency   
0       '23-3596 2023-06-01 13:30:00    Green Clean Pressure Washing  \
2       '23-3594 2023-06-01 13:15:00                   CHP - Barstow   
3       '23-3592 2023-06-01 12:07:00    California Northern Railroad   
5       '23-3590 2023-06-01 11:32:00                             NRC   
6       '23-3589 2023-06-01 11:10:00                 High Speed Rail   
...          ...                 ...                             ...   
102045         ' 2019-10-01 09:30:00  Sacramento Area Sewer District   
102047         ' 2019-10-12 01:35:00                            UPRR   
102048         ' 2019-11-12 12:38:00                   Whit O Briens   
102050         ' 2014-01-20 09:52:00                             NRC   
102051         ' 2012-08-16 03:28:00           City of Newport Beach   

          1. Type                                        Description   
0       PETROLEUM  RP stated that a waste management truck experi...  \
2        CHEMICAL  RP stated that a semi trucks breaks caught on ...   
3           OTHER  RP states: A bridge by MP 174.8 of the westval...   
5       PETROLEUM  Per NRC: "CALLER STATED THAT THREE 55 GALLON D...   
6       PETROLEUM  RP stated that they were excavating soil and t...   
...           ...                                                ...   
102045     SEWAGE  RP advised that there was a blockage in the lo...   
102047  PETROLEUM  conductorsCaller states a locomotive was leaki...   
102048  PETROLEUM  RP states: While Piledriving a hydraulic hose ...   
102050  PETROLEUM  Per NRC#1071643 "DISPENSER #9 SPILLED ROUGHLY ...   
102051     SEWAGE  RP states that a dredging company hit a sewer ...   

                                       Location           City   
0                                3835 Kern Road          Chino  \
2                      Lynwood Road Offramp I15        Lynwood   
3       MP 174.8 of the westvalley sub division        Corning   
5                                 Off of SR 118          Somis   
6                   H Street and Ventura Avenue         Fresno   
...                                         ...            ...   
102045                        9801 Beachwood Dr     Orangevale   
102047              Roseville, CA to Sparks, NV      Roseville   
102048                       1374 Pier F Avenue     Long Beach   
102050                           1804 W 11TH ST          Tracy   
102051                          1701 Bayside Dr  Newport Beach   

                       County    Zip        Incident Date  Time   
0       San Bernardino County    NaN  2023-05-31 00:00:00  1700  \
2          Los Angeles County    NaN  2023-05-31 00:00:00  2306   
3               Tehama County    NaN  2023-06-01 00:00:00  1715   
5              Ventura County    NaN  2023-06-01 00:00:00   945   
6               Fresno County    NaN  2023-06-01 00:00:00   800   
...                       ...    ...                  ...   ...   
102045      Sacramento County  95662  2019-09-03 00:00:00   831   
102047          Placer County    NaN  2019-10-11 00:00:00  2021   
102048     Los Angeles County    NaN  2019-11-12 00:00:00  1145   
102050     San Joaquin County  95376  2014-01-20 00:00:00   915   
102051          Orange County    NaN  2012-08-15 00:00:00  2300   

               Spill Site               Site        CAUSE CAUSE_Other   
0                    Road                NaN   Mechanical         NaN  \
2                    Road                NaN      Unknown         NaN   
3                    Road                NaN      Unknown         NaN   
5               Waterways  Santa Clara River        Other     Dumping   
6                   Other                NaN      Unknown         NaN   
...                   ...                ...          ...         ...   
102045          Residence        Storm Drain     Blockage         NaN   
102047          Rail Road            Unknown   Mechanical         NaN   
102048          Waterwa

#### Remove timestamp

Then, I asked Chatgpt how to remove the 00:00:00 timestamp

Chatgpt: "If all entries in the 'Incident Date' column are in the format %Y-%m-%d 00:00:00, and you want to remove the 00:00:00 part from each entry, you can use the str accessor in pandas along with strptime to convert the string to a datetime object and then use strftime to format it back without the time component."

In [63]:
hazmat_spills_clean['Incident Date'] = pd.to_datetime(hazmat_spills_clean['Incident Date'], errors='coerce')

/var/folders/s1/34kl6rwj7nx2q7mpwcv0yq1w0000gn/T/ipykernel_93301/2476742695.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hazmat_spills_clean['Incident Date'] = pd.to_datetime(hazmat_spills_clean['Incident Date'], errors='coerce')


In [64]:
hazmat_spills_clean[hazmat_spills_clean['Incident Date'].isna()]

Control#       Notified Date                       Agency    1. Type   
28284  '19-4525 2019-07-15 23:13:00                 SoCal Edison  PETROLEUM  \
49868  '16-7849 2016-12-28 07:55:00               Southern CalEd  PETROLEUM   
94997  '10-0682 2010-01-26 09:37:00  Metropolitan Water District      VAPOR   

                                             Description   
28284  Caller states a car hit the padmount, in a res...  \
49868  RP states that 10 gallons of mineral oil was r...   
94997  Caller states that maintenance activity caused...   

                                    Location       City   
28284                     8988 Kittering Dr   Oak Hills  \
49868  Tustin Ave. crossing street, 17th St.  Santa Ana   
94997               550 East Alessandro Blvd  Riverside   

                      County    Zip Incident Date  Time   
28284  San Bernardino County  92344           NaT  2245  \
49868          Orange County  92705           NaT   400   
94997       Riverside County  92508           NaT   900   

                      Spill Site Site       CAUSE CAUSE_Other Injuries YES/NO   
28284                  Residence  NaN         NaN         NaN         Unknown  \
49868                       Road  NaN   Collision         NaN              No   
94997  Treatment/Sewage Facility  NaN  Mechanical         NaN              No   

      Injuries # Fatals YES/NO Fatals # Evacs YES/NO Evacs #   
28284        NaN            No      NaN           No     NaN  \
49868        NaN            No      NaN           No     NaN   
94997        NaN            No      NaN           No     NaN   

      Drinking Water Impacted Known Impact Hour Minutes Time_Cleaned  
28284                     NaN          NaN   22      45        22:45  
49868                      No          NaN    4      00         4:00  
94997                     NaN          NaN    9      00         9:00

There are three NaT rows, I will drop these first

In [65]:
hazmat_spills_clean = hazmat_spills_clean.dropna(subset=['Incident Date'])

In [66]:
hazmat_spills_clean['Incident Date']

0        2023-05-31
2        2023-05-31
3        2023-06-01
5        2023-06-01
6        2023-06-01
            ...    
102045   2019-09-03
102047   2019-10-11
102048   2019-11-12
102050   2014-01-20
102051   2012-08-15
Name: Incident Date, Length: 101599, dtype: datetime64[ns]

In [67]:
hazmat_spills_clean['Incident Date'] = hazmat_spills_clean['Incident Date'].dt.strftime('%Y-%m-%d')

/var/folders/s1/34kl6rwj7nx2q7mpwcv0yq1w0000gn/T/ipykernel_93301/464474978.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hazmat_spills_clean['Incident Date'] = hazmat_spills_clean['Incident Date'].dt.strftime('%Y-%m-%d')


In [68]:
hazmat_spills_clean['Incident Date']

0         2023-05-31
2         2023-05-31
3         2023-06-01
5         2023-06-01
6         2023-06-01
             ...    
102045    2019-09-03
102047    2019-10-11
102048    2019-11-12
102050    2014-01-20
102051    2012-08-15
Name: Incident Date, Length: 101599, dtype: object

#### Merge the Date and Time

In [69]:
# create timestamp column (this will be a string/object data type)
hazmat_spills_clean['Incident Time'] = hazmat_spills_clean['Incident Date'] +  ' ' + hazmat_spills_clean['Time_Cleaned']

# convert timestamp column to datetime data type
hazmat_spills_clean['Incident Time'] = pd.to_datetime(hazmat_spills_clean['Incident Time'], errors='coerce')

/var/folders/s1/34kl6rwj7nx2q7mpwcv0yq1w0000gn/T/ipykernel_93301/2808676920.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hazmat_spills_clean['Incident Time'] = hazmat_spills_clean['Incident Date'] +  ' ' + hazmat_spills_clean['Time_Cleaned']
/var/folders/s1/34kl6rwj7nx2q7mpwcv0yq1w0000gn/T/ipykernel_93301/2808676920.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hazmat_spills_clean['Incident Time'] = pd.to_datetime(hazmat_spills_clean['Incident Time'], errors='coerce')


In [70]:
hazmat_spills_clean.tail()

Control#       Notified Date                          Agency   
102045        ' 2019-10-01 09:30:00  Sacramento Area Sewer District  \
102047        ' 2019-10-12 01:35:00                            UPRR   
102048        ' 2019-11-12 12:38:00                   Whit O Briens   
102050        ' 2014-01-20 09:52:00                             NRC   
102051        ' 2012-08-16 03:28:00           City of Newport Beach   

          1. Type                                        Description   
102045     SEWAGE  RP advised that there was a blockage in the lo...  \
102047  PETROLEUM  conductorsCaller states a locomotive was leaki...   
102048  PETROLEUM  RP states: While Piledriving a hydraulic hose ...   
102050  PETROLEUM  Per NRC#1071643 "DISPENSER #9 SPILLED ROUGHLY ...   
102051     SEWAGE  RP states that a dredging company hit a sewer ...   

                           Location           City              County    Zip   
102045            9801 Beachwood Dr     Orangevale   Sacramento County  95662  \
102047  Roseville, CA to Sparks, NV      Roseville       Placer County    NaN   
102048           1374 Pier F Avenue     Long Beach  Los Angeles County    NaN   
102050               1804 W 11TH ST          Tracy  San Joaquin County  95376   
102051              1701 Bayside Dr  Newport Beach       Orange County    NaN   

       Incident Date  Time         Spill Site               Site        CAUSE   
102045    2019-09-03   831          Residence        Storm Drain     Blockage  \
102047    2019-10-11  2021          Rail Road            Unknown   Mechanical   
102048    2019-11-12  1145          Waterways  Port of Longbeach   Mechanical   
102050    2014-01-20   915  Merchant/Business                NaN   Mechanical   
102051    2012-08-15  2300   Ship/Harbor/Port        Newport Bay  Human Error   

       CAUSE_Other Injuries YES/NO Injuries # Fatals YES/NO Fatals #   
102045         NaN         Unknown        NaN            No      NaN  \
102047         NaN              No        NaN            No      NaN   
102048         NaN              No        NaN            No      NaN   
102050         NaN              No        NaN            No      NaN   
102051         NaN              No        NaN            No      NaN   

       Evacs YES/NO Evacs # Drinking Water Impacted Known Impact Hour Minutes   
102045           No     NaN                     NaN          NaN    8      31  \
102047           No     NaN                 Unknown          NaN   20      21   
102048           No     NaN                     NaN          NaN   11      45   
102050           No     NaN                     NaN          NaN    9      15   
102051           No     NaN                     NaN          NaN   23      00   

       Time_Cleaned       Incident Time  
102045         8:31 2019-09-03 08:31:00  
102047        20:21 2019-10-11 20:21:00  
102048        11:45 2019-11-12 11:45:00  
102050         9:15 2014-01-20 09:15:00  
102051        23:00 2012-08-15 23:00:00

In [71]:
hazmat_spills_clean[hazmat_spills_clean['Incident Time'].isna()]

Control#       Notified Date                          Agency   
53      '23-3533 2023-05-30 13:16:00  City of Rialto Fire Department  \
56      '23-3530 2023-05-30 11:34:00                            UCLA   
130     '23-3448 2023-05-25 01:51:00                             NRC   
231     '23-3342 2023-05-21 00:09:00                             NRC   
307     '23-3262 2023-05-18 02:36:00          Union Pacific Railroad   
...          ...                 ...                             ...   
101897  '10-7858 2010-12-26 01:47:00                             NRC   
101946  '10-7907 2010-12-28 13:47:00                  USMC-Pendleton   
101978  '10-7939 2010-12-29 01:22:00          Sonoma Co Water Agency   
101979  '10-7940 2010-12-29 01:27:00          Sonoma Co Water Agency   
101982  '10-7943 2010-12-29 06:44:00            Town of Hillsborough   

            1. Type                                        Description   
53        PETROLEUM  RP stated: "Someone threw five buckets of moto...  \
56           SEWAGE  A sewage pump failed which caused the release,...   
130       PETROLEUM  Per NRC Report: Caller is reporting there was ...   
231       PETROLEUM  PER NRC REPORT:  MOTOR OIL DISCHARGED FROM A B...   
307        RAILROAD  RP States: Freight train LOE34 of the 17th, tr...   
...             ...                                                ...   
101897  UNSPECIFIED  Per NRC Report: "Caller is reporting a potenti...   
101946       SEWAGE  **Historical**  During last week's storm surge...   
101978       SEWAGE  Storm surge into collection system caused rele...   
101979       SEWAGE  Storm surge into collection system caused rele...   
101982       SEWAGE                  Release is due to the storm surge   

                                        Location            City   
53            In front of 145 West Santa Aan St.          Rialto  \
56      1250 16th St, UCLA Santa Monica Hospital    Santa Monica   
130                  Dock J7, 3850 S Harbor Blvd          Oxnard   
231         SAN ELIJO STATE BEACH; NEAR TOWER 17       Encinitas   
307                MP 699.09 of the Calexico Sub       El Centro   
...                                          ...             ...   
101897                              250 Figueroa        Monterey   
101946               Marine Memorial Golf Course  Camp Pendleton   
101978                              18715 Hwy 12          Sonoma   
101979                              17324 Hwy 12          Sonoma   
101982                              110 Hayne Rd    Hillsborough   

                       County    Zip Incident Date       Time   
53      San Bernardino County  92376    2023-05-30    Unknown  \
56         Los Angeles County  90404    2023-05-30  0745-1000   
130            Ventura County    NaN    2023-05-25         30   
231          San Diego County    NaN    2023-05-21          2   
307           Imperial County    NaN    2023-02-18   01:59:00   
...                       ...    ...           ...        ...   
101897        Monterey County  93940    2010-12-26          5   
101946       San Diego County    NaN    2010-12-22    Unknown   
101978          Sonoma County  95476    2010-12-29         30   
101979          Sonoma County  95476    2010-12-29         40   
101982       San Mateo County  94010    2010-12-29          1   

              Spill Site                                               Site   
53                  Road                                                 No  \
56                School                                        Storm Drain   
130     Ship/Harbor/Port  Channel Islands Harbor, Tributary of: Pacific ...   
231            Waterways                                      Pacific Ocean   
307            Rail Road                                                NaN   
...                  ...                                                ...   
101897  Ship/Harbor/Port                                      Pacific Ocean   
101946     Military Base

In [72]:
hazmat_spills_clean = hazmat_spills_clean.dropna(subset=['Incident Time'])
hazmat_spills_clean

Control#       Notified Date                          Agency   
0       '23-3596 2023-06-01 13:30:00    Green Clean Pressure Washing  \
2       '23-3594 2023-06-01 13:15:00                   CHP - Barstow   
3       '23-3592 2023-06-01 12:07:00    California Northern Railroad   
5       '23-3590 2023-06-01 11:32:00                             NRC   
6       '23-3589 2023-06-01 11:10:00                 High Speed Rail   
...          ...                 ...                             ...   
102045         ' 2019-10-01 09:30:00  Sacramento Area Sewer District   
102047         ' 2019-10-12 01:35:00                            UPRR   
102048         ' 2019-11-12 12:38:00                   Whit O Briens   
102050         ' 2014-01-20 09:52:00                             NRC   
102051         ' 2012-08-16 03:28:00           City of Newport Beach   

          1. Type                                        Description   
0       PETROLEUM  RP stated that a waste management truck experi...  \
2        CHEMICAL  RP stated that a semi trucks breaks caught on ...   
3           OTHER  RP states: A bridge by MP 174.8 of the westval...   
5       PETROLEUM  Per NRC: "CALLER STATED THAT THREE 55 GALLON D...   
6       PETROLEUM  RP stated that they were excavating soil and t...   
...           ...                                                ...   
102045     SEWAGE  RP advised that there was a blockage in the lo...   
102047  PETROLEUM  conductorsCaller states a locomotive was leaki...   
102048  PETROLEUM  RP states: While Piledriving a hydraulic hose ...   
102050  PETROLEUM  Per NRC#1071643 "DISPENSER #9 SPILLED ROUGHLY ...   
102051     SEWAGE  RP states that a dredging company hit a sewer ...   

                                       Location           City   
0                                3835 Kern Road          Chino  \
2                      Lynwood Road Offramp I15        Lynwood   
3       MP 174.8 of the westvalley sub division        Corning   
5                                 Off of SR 118          Somis   
6                   H Street and Ventura Avenue         Fresno   
...                                         ...            ...   
102045                        9801 Beachwood Dr     Orangevale   
102047              Roseville, CA to Sparks, NV      Roseville   
102048                       1374 Pier F Avenue     Long Beach   
102050                           1804 W 11TH ST          Tracy   
102051                          1701 Bayside Dr  Newport Beach   

                       County    Zip Incident Date  Time         Spill Site   
0       San Bernardino County    NaN    2023-05-31  1700               Road  \
2          Los Angeles County    NaN    2023-05-31  2306               Road   
3               Tehama County    NaN    2023-06-01  1715               Road   
5              Ventura County    NaN    2023-06-01   945          Waterways   
6               Fresno County    NaN    2023-06-01   800              Other   
...                       ...    ...           ...   ...                ...   
102045      Sacramento County  95662    2019-09-03   831          Residence   
102047          Placer County    NaN    2019-10-11  2021          Rail Road   
102048     Los Angeles County    NaN    2019-11-12  1145          Waterways   
102050     San Joaquin County  95376    2014-01-20   915  Merchant/Business   
102051          Orange County    NaN    2012-08-15  2300   Ship/Harbor/Port   

                     Site        CAUSE CAUSE_Other Injuries YES/NO Injuries #   
0                     NaN   Mechanical         NaN              No        NaN  \
2                     NaN      Unknown         NaN              No        NaN   
3                     NaN      Unknown         NaN              No        NaN   
5       Santa Clara River        Other     Dumping              No        NaN   
6                     NaN      Unknown         NaN              No        NaN   
...                   ...          ...         ...

In [73]:
hazmat_spills_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99196 entries, 0 to 102051
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype         
---  ------                   --------------  -----         
 0   Control#                 99196 non-null  object        
 1   Notified Date            99196 non-null  datetime64[ns]
 2   Agency                   99122 non-null  object        
 3   1. Type                  99196 non-null  object        
 4   Description              99196 non-null  object        
 5   Location                 99194 non-null  object        
 6   City                     99186 non-null  object        
 7   County                   99176 non-null  object        
 8   Zip                      53072 non-null  object        
 9   Incident Date            99196 non-null  object        
 10  Time                     99196 non-null  object        
 11  Spill Site               99196 non-null  object        
 12  Site                     35236 non-n

Now I am done with all the time-related columns!

## Clean the Type Column

### Normalizing the strings

Since the text format of some entries in the Type column are mixed, I need to normalize them first

In [74]:
hazmat_spills_clean['1. Type'] = hazmat_spills['1. Type'].str.lower()
hazmat_spills_clean

Control#       Notified Date                          Agency   
0       '23-3596 2023-06-01 13:30:00    Green Clean Pressure Washing  \
2       '23-3594 2023-06-01 13:15:00                   CHP - Barstow   
3       '23-3592 2023-06-01 12:07:00    California Northern Railroad   
5       '23-3590 2023-06-01 11:32:00                             NRC   
6       '23-3589 2023-06-01 11:10:00                 High Speed Rail   
...          ...                 ...                             ...   
102045         ' 2019-10-01 09:30:00  Sacramento Area Sewer District   
102047         ' 2019-10-12 01:35:00                            UPRR   
102048         ' 2019-11-12 12:38:00                   Whit O Briens   
102050         ' 2014-01-20 09:52:00                             NRC   
102051         ' 2012-08-16 03:28:00           City of Newport Beach   

          1. Type                                        Description   
0       petroleum  RP stated that a waste management truck experi...  \
2        chemical  RP stated that a semi trucks breaks caught on ...   
3           other  RP states: A bridge by MP 174.8 of the westval...   
5       petroleum  Per NRC: "CALLER STATED THAT THREE 55 GALLON D...   
6       petroleum  RP stated that they were excavating soil and t...   
...           ...                                                ...   
102045     sewage  RP advised that there was a blockage in the lo...   
102047     sewage  conductorsCaller states a locomotive was leaki...   
102048  petroleum  RP states: While Piledriving a hydraulic hose ...   
102050   chemical  Per NRC#1071643 "DISPENSER #9 SPILLED ROUGHLY ...   
102051      other  RP states that a dredging company hit a sewer ...   

                                       Location           City   
0                                3835 Kern Road          Chino  \
2                      Lynwood Road Offramp I15        Lynwood   
3       MP 174.8 of the westvalley sub division        Corning   
5                                 Off of SR 118          Somis   
6                   H Street and Ventura Avenue         Fresno   
...                                         ...            ...   
102045                        9801 Beachwood Dr     Orangevale   
102047              Roseville, CA to Sparks, NV      Roseville   
102048                       1374 Pier F Avenue     Long Beach   
102050                           1804 W 11TH ST          Tracy   
102051                          1701 Bayside Dr  Newport Beach   

                       County    Zip Incident Date  Time         Spill Site   
0       San Bernardino County    NaN    2023-05-31  1700               Road  \
2          Los Angeles County    NaN    2023-05-31  2306               Road   
3               Tehama County    NaN    2023-06-01  1715               Road   
5              Ventura County    NaN    2023-06-01   945          Waterways   
6               Fresno County    NaN    2023-06-01   800              Other   
...                       ...    ...           ...   ...                ...   
102045      Sacramento County  95662    2019-09-03   831          Residence   
102047          Placer County    NaN    2019-10-11  2021          Rail Road   
102048     Los Angeles County    NaN    2019-11-12  1145          Waterways   
102050     San Joaquin County  95376    2014-01-20   915  Merchant/Business   
102051          Orange County    NaN    2012-08-15  2300   Ship/Harbor/Port   

                     Site        CAUSE CAUSE_Other Injuries YES/NO Injuries #   
0                     NaN   Mechanical         NaN              No        NaN  \
2                     NaN      Unknown         NaN              No        NaN   
3                     NaN      Unknown         NaN              No        NaN   
5       Santa Clara River        Other     Dumping              No        NaN   
6                     NaN      Unknown         NaN              No        NaN   
...                   ...          ...         ...

## Clean Address and Geocoding

Since there are many missing data in Zip column, I will drop it first and then use Geocodio to generate zip code

In [75]:
hazmat_spills_clean=hazmat_spills_clean.drop(columns='Zip', axis=1)

In [76]:
hazmat_spills_clean.reset_index(drop=True)

Control#       Notified Date                          Agency   
0      '23-3596 2023-06-01 13:30:00    Green Clean Pressure Washing  \
1      '23-3594 2023-06-01 13:15:00                   CHP - Barstow   
2      '23-3592 2023-06-01 12:07:00    California Northern Railroad   
3      '23-3590 2023-06-01 11:32:00                             NRC   
4      '23-3589 2023-06-01 11:10:00                 High Speed Rail   
...         ...                 ...                             ...   
99191         ' 2019-10-01 09:30:00  Sacramento Area Sewer District   
99192         ' 2019-10-12 01:35:00                            UPRR   
99193         ' 2019-11-12 12:38:00                   Whit O Briens   
99194         ' 2014-01-20 09:52:00                             NRC   
99195         ' 2012-08-16 03:28:00           City of Newport Beach   

         1. Type                                        Description   
0      petroleum  RP stated that a waste management truck experi...  \
1       chemical  RP stated that a semi trucks breaks caught on ...   
2          other  RP states: A bridge by MP 174.8 of the westval...   
3      petroleum  Per NRC: "CALLER STATED THAT THREE 55 GALLON D...   
4      petroleum  RP stated that they were excavating soil and t...   
...          ...                                                ...   
99191     sewage  RP advised that there was a blockage in the lo...   
99192     sewage  conductorsCaller states a locomotive was leaki...   
99193  petroleum  RP states: While Piledriving a hydraulic hose ...   
99194   chemical  Per NRC#1071643 "DISPENSER #9 SPILLED ROUGHLY ...   
99195      other  RP states that a dredging company hit a sewer ...   

                                      Location           City   
0                               3835 Kern Road          Chino  \
1                     Lynwood Road Offramp I15        Lynwood   
2      MP 174.8 of the westvalley sub division        Corning   
3                                Off of SR 118          Somis   
4                  H Street and Ventura Avenue         Fresno   
...                                        ...            ...   
99191                        9801 Beachwood Dr     Orangevale   
99192              Roseville, CA to Sparks, NV      Roseville   
99193                       1374 Pier F Avenue     Long Beach   
99194                           1804 W 11TH ST          Tracy   
99195                          1701 Bayside Dr  Newport Beach   

                      County Incident Date  Time         Spill Site   
0      San Bernardino County    2023-05-31  1700               Road  \
1         Los Angeles County    2023-05-31  2306               Road   
2              Tehama County    2023-06-01  1715               Road   
3             Ventura County    2023-06-01   945          Waterways   
4              Fresno County    2023-06-01   800              Other   
...                      ...           ...   ...                ...   
99191      Sacramento County    2019-09-03   831          Residence   
99192          Placer County    2019-10-11  2021          Rail Road   
99193     Los Angeles County    2019-11-12  1145          Waterways   
99194     San Joaquin County    2014-01-20   915  Merchant/Business   
99195          Orange County    2012-08-15  2300   Ship/Harbor/Port   

                    Site        CAUSE CAUSE_Other Injuries YES/NO Injuries #   
0                    NaN   Mechanical         NaN              No        NaN  \
1                    NaN      Unknown         NaN              No        NaN   
2                    NaN      Unknown         NaN              No        NaN   
3      Santa Clara River        Other     Dumping              No        NaN   
4                    NaN      Unknown         NaN              No        NaN   
...                  ...          ...         ...             ...        ...   
99191        Storm Drain     Blockage         NaN         Unknown        NaN   
99192            Unknown   

### Drop Duplicates

In [77]:
hazmat_spills_clean[hazmat_spills_clean['Location'].isna()]

Control#       Notified Date                 Agency    1. Type   
32951  '18-8477 2018-12-13 08:01:00  E&B Natural Resources      other  \
59477  '15-2236 2015-04-21 12:22:00                    NaN  petroleum   

                                             Description Location   
32951  Caller stated that the release was due to mech...      NaN  \
59477                                                         NaN   

              City       County Incident Date  Time        Spill Site Site   
32951  Bakersfield  Kern County    2018-12-13   740         Oil Field  NaN  \
59477          NaN          NaN    2015-04-21  1200  Ship/Harbor/Port  NaN   

            CAUSE CAUSE_Other Injuries YES/NO Injuries # Fatals YES/NO   
32951  Mechanical         NaN              No        NaN            No  \
59477         NaN         NaN              No        NaN            No   

      Fatals # Evacs YES/NO Evacs # Drinking Water Impacted Known Impact Hour   
32951      NaN           No     NaN                      No          NaN    7  \
59477      NaN           No     NaN                     NaN          NaN   12   

      Minutes Time_Cleaned       Incident Time  
32951      40         7:40 2018-12-13 07:40:00  
59477      00        12:00 2015-04-21 12:00:00

In [78]:
hazmat_spills_clean.dropna(subset=['Location'], inplace=True)

In [79]:
hazmat_spills_clean

Control#       Notified Date                          Agency   
0       '23-3596 2023-06-01 13:30:00    Green Clean Pressure Washing  \
2       '23-3594 2023-06-01 13:15:00                   CHP - Barstow   
3       '23-3592 2023-06-01 12:07:00    California Northern Railroad   
5       '23-3590 2023-06-01 11:32:00                             NRC   
6       '23-3589 2023-06-01 11:10:00                 High Speed Rail   
...          ...                 ...                             ...   
102045         ' 2019-10-01 09:30:00  Sacramento Area Sewer District   
102047         ' 2019-10-12 01:35:00                            UPRR   
102048         ' 2019-11-12 12:38:00                   Whit O Briens   
102050         ' 2014-01-20 09:52:00                             NRC   
102051         ' 2012-08-16 03:28:00           City of Newport Beach   

          1. Type                                        Description   
0       petroleum  RP stated that a waste management truck experi...  \
2        chemical  RP stated that a semi trucks breaks caught on ...   
3           other  RP states: A bridge by MP 174.8 of the westval...   
5       petroleum  Per NRC: "CALLER STATED THAT THREE 55 GALLON D...   
6       petroleum  RP stated that they were excavating soil and t...   
...           ...                                                ...   
102045     sewage  RP advised that there was a blockage in the lo...   
102047     sewage  conductorsCaller states a locomotive was leaki...   
102048  petroleum  RP states: While Piledriving a hydraulic hose ...   
102050   chemical  Per NRC#1071643 "DISPENSER #9 SPILLED ROUGHLY ...   
102051      other  RP states that a dredging company hit a sewer ...   

                                       Location           City   
0                                3835 Kern Road          Chino  \
2                      Lynwood Road Offramp I15        Lynwood   
3       MP 174.8 of the westvalley sub division        Corning   
5                                 Off of SR 118          Somis   
6                   H Street and Ventura Avenue         Fresno   
...                                         ...            ...   
102045                        9801 Beachwood Dr     Orangevale   
102047              Roseville, CA to Sparks, NV      Roseville   
102048                       1374 Pier F Avenue     Long Beach   
102050                           1804 W 11TH ST          Tracy   
102051                          1701 Bayside Dr  Newport Beach   

                       County Incident Date  Time         Spill Site   
0       San Bernardino County    2023-05-31  1700               Road  \
2          Los Angeles County    2023-05-31  2306               Road   
3               Tehama County    2023-06-01  1715               Road   
5              Ventura County    2023-06-01   945          Waterways   
6               Fresno County    2023-06-01   800              Other   
...                       ...           ...   ...                ...   
102045      Sacramento County    2019-09-03   831          Residence   
102047          Placer County    2019-10-11  2021          Rail Road   
102048     Los Angeles County    2019-11-12  1145          Waterways   
102050     San Joaquin County    2014-01-20   915  Merchant/Business   
102051          Orange County    2012-08-15  2300   Ship/Harbor/Port   

                     Site        CAUSE CAUSE_Other Injuries YES/NO Injuries #   
0                     NaN   Mechanical         NaN              No        NaN  \
2                     NaN      Unknown         NaN              No        NaN   
3                     NaN      Unknown         NaN              No        NaN   
5       Santa Clara River        Other     Dumping              No        NaN   
6                     NaN      Unknown         NaN              No        NaN   
...                   ...          ...         ...             ...        ...   
102045        Storm Drain     Blockage         NaN   

In [80]:
hazmat_spills_clean[hazmat_spills_clean['City'].isna()]

Control#       Notified Date                        Agency   
35485  '18-5770 2018-08-27 09:47:00                     Cal Trans  \
53077  '16-4437 2016-07-22 01:30:00              Private Citizen,   
56580  '16-0749 2016-02-03 16:06:00                     Anonymous   
64382  '15-7406 2015-12-18 09:20:00                        DELETE   
88104  '11-1170 2011-02-25 12:56:00                           NRC   
95539  '10-1233 2010-02-17 07:54:00                           NRC   
96125  '10-1839 2010-03-16 17:12:00        Matson Navigation Comp   
98211  '10-4003 2010-07-01 13:59:00  U.S. Army Corps of Engineers   
99227  '10-5046 2010-08-23 20:19:00                       US Navy   

            1. Type                                        Description   
35485     petroleum  RP states: 2 big rigs were involved in an acci...  \
53077  radiological  ***Historical Report*** RP States: Some guy fr...   
56580      railroad  ****************THIS CALL IS IN NEW HAMPSHIRE ...   
64382         vapor                              DELETE - Not sent out   
88104      chemical  HISTORICAL:  Incident was discovered 2/23/11. ...   
95539     petroleum  per NRC fax:  "Caller is reporting a release o...   
96125     petroleum  HISTORICAL and EARLY NOTIFICATION,  RP States:...   
98211     petroleum  The caller is reporting that a hydraulic hose ...   
99227         other  NRC report reads: Fuel discharged from the eng...   

                                                Location City   
35485  Contra Costa County Southbound 160 at West bou...  NaN  \
53077                                     Continental US  NaN   
56580                              53 Allen Hasting Way   NaN   
64382                              DELETE - Not sent out  NaN   
88104                                     LT 8 LLNR-6165  NaN   
95539  Section:  3;   Township:  11 North; Range:  9 ...  NaN   
96125               1 week outside of  Long Beach Harbor  NaN   
98211  San Pablo Bay, Latitude 38° 01.2' N, Longitude...  NaN   
99227                10 NM off San Diego (Pacific Ocean)  NaN   

                     County Incident Date  Time                  Spill Site   
35485                   NaN    2018-08-27   615                        Road  \
53077                   NaN    2016-07-21   128                   Residence   
56580                   NaN    2016-02-01  1200           Merchant/Business   
64382                   NaN    2015-12-18   748                       Other   
88104  San Francisco County    2011-02-23  1030                   Waterways   
95539         Sonoma County    2010-02-16   730                       Other   
96125    Los Angeles County    2010-03-10   800            Ship/Harbor/Port   
98211          Marin County    2010-07-01  1330  Waterways,Ship/Harbor/Port   
99227      San Diego County    2010-08-23  1824                       Other   

                    Site        CAUSE            CAUSE_Other Injuries YES/NO   
35485                NaN    Collision                    NaN              No  \
53077     Continental US      Unknown                    NaN              No   
56580                NaN      Unknown                    NaN              No   
64382                NaN        Other  DELETE - Not sent out              No   
88104         Napa River      Unknown                    NaN              No   
95539                NaN        Other               Drilling              No   
96125                NaN      Unknown                    NaN              No   
98211  San Francisco Bay   Mechanical                    NaN              No   
99227                  Y  Human Error                    NaN              No   

      Injuries # Fatals YES/NO Fatals # Evacs YES/NO Evacs #   
35485        NaN            No      NaN           No     NaN  \
53077        NaN            No      NaN           No     NaN   
56580        NaN            No      NaN           No     NaN   
64382        NaN            No      NaN           No     NaN   
88104       

In [81]:
hazmat_spills_clean.dropna(subset=['City'], inplace=True)

In [82]:
hazmat_spills_clean

Control#       Notified Date                          Agency   
0       '23-3596 2023-06-01 13:30:00    Green Clean Pressure Washing  \
2       '23-3594 2023-06-01 13:15:00                   CHP - Barstow   
3       '23-3592 2023-06-01 12:07:00    California Northern Railroad   
5       '23-3590 2023-06-01 11:32:00                             NRC   
6       '23-3589 2023-06-01 11:10:00                 High Speed Rail   
...          ...                 ...                             ...   
102045         ' 2019-10-01 09:30:00  Sacramento Area Sewer District   
102047         ' 2019-10-12 01:35:00                            UPRR   
102048         ' 2019-11-12 12:38:00                   Whit O Briens   
102050         ' 2014-01-20 09:52:00                             NRC   
102051         ' 2012-08-16 03:28:00           City of Newport Beach   

          1. Type                                        Description   
0       petroleum  RP stated that a waste management truck experi...  \
2        chemical  RP stated that a semi trucks breaks caught on ...   
3           other  RP states: A bridge by MP 174.8 of the westval...   
5       petroleum  Per NRC: "CALLER STATED THAT THREE 55 GALLON D...   
6       petroleum  RP stated that they were excavating soil and t...   
...           ...                                                ...   
102045     sewage  RP advised that there was a blockage in the lo...   
102047     sewage  conductorsCaller states a locomotive was leaki...   
102048  petroleum  RP states: While Piledriving a hydraulic hose ...   
102050   chemical  Per NRC#1071643 "DISPENSER #9 SPILLED ROUGHLY ...   
102051      other  RP states that a dredging company hit a sewer ...   

                                       Location           City   
0                                3835 Kern Road          Chino  \
2                      Lynwood Road Offramp I15        Lynwood   
3       MP 174.8 of the westvalley sub division        Corning   
5                                 Off of SR 118          Somis   
6                   H Street and Ventura Avenue         Fresno   
...                                         ...            ...   
102045                        9801 Beachwood Dr     Orangevale   
102047              Roseville, CA to Sparks, NV      Roseville   
102048                       1374 Pier F Avenue     Long Beach   
102050                           1804 W 11TH ST          Tracy   
102051                          1701 Bayside Dr  Newport Beach   

                       County Incident Date  Time         Spill Site   
0       San Bernardino County    2023-05-31  1700               Road  \
2          Los Angeles County    2023-05-31  2306               Road   
3               Tehama County    2023-06-01  1715               Road   
5              Ventura County    2023-06-01   945          Waterways   
6               Fresno County    2023-06-01   800              Other   
...                       ...           ...   ...                ...   
102045      Sacramento County    2019-09-03   831          Residence   
102047          Placer County    2019-10-11  2021          Rail Road   
102048     Los Angeles County    2019-11-12  1145          Waterways   
102050     San Joaquin County    2014-01-20   915  Merchant/Business   
102051          Orange County    2012-08-15  2300   Ship/Harbor/Port   

                     Site        CAUSE CAUSE_Other Injuries YES/NO Injuries #   
0                     NaN   Mechanical         NaN              No        NaN  \
2                     NaN      Unknown         NaN              No        NaN   
3                     NaN      Unknown         NaN              No        NaN   
5       Santa Clara River        Other     Dumping              No        NaN   
6                     NaN      Unknown         NaN              No        NaN   
...                   ...          ...         ...             ...        ...   
102045        Storm Drain     Blockage         NaN   

In [83]:
hazmat_spills_clean[hazmat_spills_clean['County'].isna()]

Control#       Notified Date                           Agency   
1770   '23-1719 2023-03-09 22:39:00       Sonoma County Water Agency  \
8934   '22-1916 2022-04-05 12:20:00                      CHP Coastal   
20357  '20-4535 2020-08-20 07:13:00             Ventura County Fire    
26090  '19-6874 2019-10-25 12:15:00  Dept. of Public Works LA County   
28210  '19-4604 2019-07-18 15:29:00                              NRC   
29022  '19-3746 2019-06-11 18:01:00   Freeport - McMoran Oil and Gas   
53484  '16-4019 2016-07-01 15:39:00                   Private Vessel   
54692  '16-2717 2016-05-07 11:40:00                          Chevron   
56924  '16-0399 2016-01-19 11:06:00                          SCFuels   
59027  '15-1764 2015-03-29 10:18:00                      S CA Edison   
61968  '15-4853 2015-08-19 13:30:00                             UPRR   
63277  '15-6233 2015-10-21 17:29:00                           DELETE   
66125  '14-1542 2014-03-13 14:29:00                              NRC   
76439  '13-4950 2013-08-11 20:39:00     Freeport McMoRan Oil and Gas   
77213  '13-5749 2013-09-12 22:15:00             Los Angeles Co. Fire   

           1. Type                                        Description   
1770        sewage  RP states: A Storm surge caused the release of...  \
8934     petroleum  RP states, a generator fell out of a pickup ve...   
20357     railroad  Caller states semi truck swerved to avoid hitt...   
26090        vapor  RP states: A blockage in the main line was the...   
28210    petroleum  Per NRC report" CALLER REPORTED A TRUCK WAS HO...   
29022        vapor  CALLER REPORTS THAT WHILE PUMPING OUT A TANK, ...   
53484     chemical  Caller stated that they have a release of less...   
54692       sewage  Customer overfill caused this release to aspha...   
56924       sewage  RP states driver was filling tank, valve on ta...   
59027    petroleum  Vehicle accident involving a vault cable and g...   
61968     railroad  Caller states:  A crew working in the area rep...   
63277       sewage                                   Refer to 15-6232   
66125    petroleum  Per NRC report: "CALLER STATED DUE TO BAD WEAT...   
76439        other  RP is reporting that a malfunctioning over flo...   
77213  unspecified  DELETE: THIS IS A DUPLICATE OF 13-5748 A compa...   

                                                Location   
1770                                    17324 Highway 12  \
8934                HWY 35, just South of Bear Creek Rd    
20357                South bound 101, south of canyon rd   
26090                               2500 Wellesley Drive   
28210                             4830 Las Virgenes Road   
29022  Latitude: 34° 28' 06" N Longitude: 120° 40' 51...   
53484                  Belingham Marina, Sawtooth Dock,    
54692                                3260 Wagon train Rd   
56924                                   1475 E Shore Hwy   
59027                      7067 Hamner Ave (Eastvale FD)   
61968  BNSF Interchange Yard // Railroad Ave. x Parks...   
63277                                             DELETE   
66125  Latitude: 43° 47' 00" N Longitude: 153° 21' 00...   
76439      Township 32 South , Range 23 East, Section 22   
77213  11305 S. Truro Ave. Hawthorne, Los Angeles County   

                                                   City County Incident Date   
1770                                            Sonoma     NaN    2023-03-09  \
8934                                    Lexington Hills    NaN    2022-04-05   
20357            Unincorporated county north of Ventura    NaN    2020-08-20   
26090            Unincorporated county area Los Angeles    NaN    2019-10-24   
28210                                        Calabassas    NaN    2019-07-18   
29022                                  Platform Harvest    NaN    2019-06-11   
53484                                        Bellingham    NaN    2016-07-01   
54692  Unincorporated Area San Bernardino Northern area    NaN    2016-05-07   
5692

In [84]:
hazmat_spills_clean.dropna(subset=['County'], inplace=True)

### Merge Street Address, City and County
Since the street address, city and county are different columns, I will go to merge them.

In [85]:
hazmat_spills_clean['address'] = (
    hazmat_spills_clean['Location'].astype(str) + ',' +
    hazmat_spills_clean['City'].astype(str) + ',' +
    hazmat_spills_clean['County'].astype(str)
)

I encountered an error: TypeError: unsupported operand type(s) for +: 'int' and 'str'

I asked Chatgpt why this error occurred

Chatgpt: "The error you're encountering (TypeError: unsupported operand type(s) for +: 'int' and 'str') suggests that you are trying to concatenate (using the + operator) columns that contain both integer and string values. This operation is not allowed because the + operator is ambiguous when dealing with different data types. It seems like **one or more of the columns Location, City, or County may contain integer values**. To resolve this issue, **you can convert the integer values to strings before performing the concatenation. You can use the astype method to convert the columns to strings**"

so I made the change as above

In [86]:
hazmat_spills_clean

Control#       Notified Date                          Agency   
0       '23-3596 2023-06-01 13:30:00    Green Clean Pressure Washing  \
2       '23-3594 2023-06-01 13:15:00                   CHP - Barstow   
3       '23-3592 2023-06-01 12:07:00    California Northern Railroad   
5       '23-3590 2023-06-01 11:32:00                             NRC   
6       '23-3589 2023-06-01 11:10:00                 High Speed Rail   
...          ...                 ...                             ...   
102045         ' 2019-10-01 09:30:00  Sacramento Area Sewer District   
102047         ' 2019-10-12 01:35:00                            UPRR   
102048         ' 2019-11-12 12:38:00                   Whit O Briens   
102050         ' 2014-01-20 09:52:00                             NRC   
102051         ' 2012-08-16 03:28:00           City of Newport Beach   

          1. Type                                        Description   
0       petroleum  RP stated that a waste management truck experi...  \
2        chemical  RP stated that a semi trucks breaks caught on ...   
3           other  RP states: A bridge by MP 174.8 of the westval...   
5       petroleum  Per NRC: "CALLER STATED THAT THREE 55 GALLON D...   
6       petroleum  RP stated that they were excavating soil and t...   
...           ...                                                ...   
102045     sewage  RP advised that there was a blockage in the lo...   
102047     sewage  conductorsCaller states a locomotive was leaki...   
102048  petroleum  RP states: While Piledriving a hydraulic hose ...   
102050   chemical  Per NRC#1071643 "DISPENSER #9 SPILLED ROUGHLY ...   
102051      other  RP states that a dredging company hit a sewer ...   

                                       Location           City   
0                                3835 Kern Road          Chino  \
2                      Lynwood Road Offramp I15        Lynwood   
3       MP 174.8 of the westvalley sub division        Corning   
5                                 Off of SR 118          Somis   
6                   H Street and Ventura Avenue         Fresno   
...                                         ...            ...   
102045                        9801 Beachwood Dr     Orangevale   
102047              Roseville, CA to Sparks, NV      Roseville   
102048                       1374 Pier F Avenue     Long Beach   
102050                           1804 W 11TH ST          Tracy   
102051                          1701 Bayside Dr  Newport Beach   

                       County Incident Date  Time         Spill Site   
0       San Bernardino County    2023-05-31  1700               Road  \
2          Los Angeles County    2023-05-31  2306               Road   
3               Tehama County    2023-06-01  1715               Road   
5              Ventura County    2023-06-01   945          Waterways   
6               Fresno County    2023-06-01   800              Other   
...                       ...           ...   ...                ...   
102045      Sacramento County    2019-09-03   831          Residence   
102047          Placer County    2019-10-11  2021          Rail Road   
102048     Los Angeles County    2019-11-12  1145          Waterways   
102050     San Joaquin County    2014-01-20   915  Merchant/Business   
102051          Orange County    2012-08-15  2300   Ship/Harbor/Port   

                     Site        CAUSE CAUSE_Other Injuries YES/NO Injuries #   
0                     NaN   Mechanical         NaN              No        NaN  \
2                     NaN      Unknown         NaN              No        NaN   
3                     NaN      Unknown         NaN              No        NaN   
5       Santa Clara River        Other     Dumping              No        NaN   
6                     NaN      Unknown         NaN              No        NaN   
...                   ...          ...         ...             ...        ...   
102045        Storm Drain     Blockage         NaN   

### Export Dataset

In [87]:
hazmat_spills_clean.to_csv('hazmat_spills_clean.csv', index=False) 

### Dedupe addresses

In [88]:
address = hazmat_spills_clean[['address']].copy()
address

address
0              3835 Kern Road,Chino,San Bernardino County
2       Lynwood Road Offramp I15,Lynwood,Los Angeles C...
3       MP 174.8 of the westvalley sub division,Cornin...
5                      Off of SR 118,Somis,Ventura County
6        H Street and Ventura Avenue,Fresno,Fresno County
...                                                   ...
102045     9801 Beachwood Dr,Orangevale,Sacramento County
102047  Roseville, CA to Sparks, NV,Roseville,Placer C...
102048   1374 Pier F Avenue,Long Beach,Los Angeles County
102050            1804 W 11TH ST,Tracy,San Joaquin County
102051        1701 Bayside Dr,Newport Beach,Orange County

[99170 rows x 1 columns]

In [89]:
address = address.drop_duplicates().reset_index(drop=True)
address

address
0             3835 Kern Road,Chino,San Bernardino County
1      Lynwood Road Offramp I15,Lynwood,Los Angeles C...
2      MP 174.8 of the westvalley sub division,Cornin...
3                     Off of SR 118,Somis,Ventura County
4       H Street and Ventura Avenue,Fresno,Fresno County
...                                                  ...
88754  25 WATER FRONT DR, HUMBOLDT BAY,Eureka,Humbold...
88755                          asdf,Merced,Merced County
88756  2121 Hanscom Dr,Santa Fe Springs,Los Angeles C...
88757                     xxxx,Acampo,San Joaquin County
88758   1374 Pier F Avenue,Long Beach,Los Angeles County

[88759 rows x 1 columns]

### Subsetting Address in Richmond

Since there are too many rows, I will just look at address in Richmond

In [90]:
address_richmond=address[address['address'].str.contains('Richmond')]

In [91]:
address_richmond

address
165    2231 Green Ridge Drive,Richmond,Contra Costa C...
196          740 Spring St.,Richmond,Contra Costa County
495    Parkway way Drive x Park Central,Richmond,Cont...
537    MP: 10.75, SUB: Martinez,Richmond,Contra Costa...
586       3110 regatta Blvd,Richmond,Contra Costa County
...                                                  ...
88446  Ohai Road & Richmond Road,Santa Paula,Ventura ...
88646  1340 Marina Way South Slip D-141A, D-Dock ,Ric...
88695  860 harbour Way South,Richmond,Contra Costa Co...
88698  2755 Isaabel St (Isabel Facility),Richmond,Con...
88712    3410 Barrett Ave. ,Richmond,Contra Costa County

[859 rows x 1 columns]

In [92]:
address_richmond=address_richmond[address_richmond['address'].str.contains('Contra Costa')]

In [93]:
address_richmond

address
165    2231 Green Ridge Drive,Richmond,Contra Costa C...
196          740 Spring St.,Richmond,Contra Costa County
495    Parkway way Drive x Park Central,Richmond,Cont...
537    MP: 10.75, SUB: Martinez,Richmond,Contra Costa...
586       3110 regatta Blvd,Richmond,Contra Costa County
...                                                  ...
88421     1306 Channel Blvd,Richmond,Contra Costa County
88646  1340 Marina Way South Slip D-141A, D-Dock ,Ric...
88695  860 harbour Way South,Richmond,Contra Costa Co...
88698  2755 Isaabel St (Isabel Facility),Richmond,Con...
88712    3410 Barrett Ave. ,Richmond,Contra Costa County

[833 rows x 1 columns]

### Export intersections to geocode

In [94]:
address_richmond.to_csv('address_richmond.csv', index=False)

### Import the Geocodio file

In [95]:
geocodio_csv_name = 'address_richmond_geocodio_64556faae4c852f314a4c16617ce344406e63b98.csv'
geocoded = pd.read_csv(geocodio_csv_name)

In [96]:
geocoded.tail(3)

address   Latitude   Longitude   
830  860 harbour Way South,Richmond,Contra Costa Co...  37.920138 -122.359448  \
831  2755 Isaabel St (Isabel Facility),Richmond,Con...  37.897055 -122.321880   
832    3410 Barrett Ave. ,Richmond,Contra Costa County  37.936604 -122.336033   

     Accuracy Score        Accuracy Type Number         Street Unit Type   
830            1.00              rooftop    860  Harbour Way S       NaN  \
831            1.00  range_interpolation   2755      Isabel St       NaN   
832            0.95              rooftop   3410    Barrett Ave       NaN   

    Unit Number      City State               County      Zip Country   
830         NaN  Richmond    CA  Contra Costa County  94804.0      US  \
831         NaN  Richmond    CA  Contra Costa County  94804.0      US   
832         NaN  Richmond    CA  Contra Costa County  94805.0      US   

                                            Source   
830                            Contra Costa County  \
831  TIGER/Line® dataset from the US Census Bureau   
832                            Contra Costa County   

     ACS Economics/Number of households/Total/Value   
830                                           950.0  \
831                                           985.0   
832                                           412.0   

     ACS Economics/Number of households/Total/Margin of error   
830                                              330.0         \
831                                              147.0          
832                                              137.0          

     ACS Economics/Median household income/Total/Value   
830                                           107880.0  \
831                                           105945.0   
832                                            88125.0   

     ACS Economics/Median household income/Total/Margin of error   
830                                            52395.0            \
831                                            10039.0             
832                                            22284.0             

     ACS Economics/Household income/Less than $10,000/Value   
830                                               13.0       \
831                                               28.0        
832                                                0.0        

     ACS Economics/Household income/Less than $10,000/Margin of error   
830                                               21.0                 \
831                                               28.0                  
832                                               13.0                  

     ACS Economics/Household income/Less than $10,000/Percentage   
830                                              0.014            \
831                                              0.028             
832                                              0.000             

     ACS Economics/Household income/$10,000 to $14,999/Value   
830                                               17.0        \
831                                               47.0         
832                                                0.0         

     ACS Economics/Household income/$10,000 to $14,999/Margin of error   
830                                               41.0                  \
831                                               49.0                   
832                                               13.0                   

     ACS Economics/Household income/$10,000 to $14,999/Percentage   
830                                              0.018             \
831                                              0.048              
832                                              0.000              

     ACS Economics/Household income/$15,000 to $19,999/Value   
830                                                0.0        \
831                                                0.0         
832                                                5.0         

     ACS Eco

### Reduce Columns

There are many columns that Geocodio gave me for the household income and demographics, I will subset a few of them

In [97]:
geocoded.columns

Index(['address', 'Latitude', 'Longitude', 'Accuracy Score', 'Accuracy Type',
       'Number', 'Street', 'Unit Type', 'Unit Number', 'City',
       ...
       'ACS Demographics/Race and ethnicity/Hispanic or Latino: Some other race alone/Percentage',
       'ACS Demographics/Race and ethnicity/Hispanic or Latino: Two or more races/Value',
       'ACS Demographics/Race and ethnicity/Hispanic or Latino: Two or more races/Margin of error',
       'ACS Demographics/Race and ethnicity/Hispanic or Latino: Two or more races/Percentage',
       'ACS Demographics/Race and ethnicity/Hispanic or Latino: Two or more races: Two races including Some other race/Value',
       'ACS Demographics/Race and ethnicity/Hispanic or Latino: Two or more races: Two races including Some other race/Margin of error',
       'ACS Demographics/Race and ethnicity/Hispanic or Latino: Two or more races: Two races including Some other race/Percentage',
       'ACS Demographics/Race and ethnicity/Hispanic or Latino: Two 

In [98]:
geocoded = geocoded[[
    'address', 'Latitude', 'Longitude', 'Accuracy Score',
    'Accuracy Type', 'City', 'State', 'County', 'Zip', 'ACS Economics/Median household income/Total/Value',
    'ACS Economics/Median household income/Total/Margin of error', 'ACS Demographics/Median age/Total/Value', 
    'ACS Demographics/Median age/Total/Margin of error', 'ACS Demographics/Race and ethnicity/Not Hispanic or Latino: White alone/Percentage',
    'ACS Demographics/Race and ethnicity/Not Hispanic or Latino: Black or African American alone/Percentage', 
    'ACS Demographics/Race and ethnicity/Not Hispanic or Latino: American Indian and Alaska Native alone/Percentage',
    'ACS Demographics/Race and ethnicity/Not Hispanic or Latino: Asian alone/Percentage', 
    'ACS Demographics/Race and ethnicity/Not Hispanic or Latino: Native Hawaiian and Other Pacific Islander alone/Percentage'  
]].copy()
geocoded

address   Latitude   Longitude   
0    2231 Green Ridge Drive,Richmond,Contra Costa C...  37.963141 -122.296587  \
1          740 Spring St.,Richmond,Contra Costa County  37.922267 -122.335606   
2    Parkway way Drive x Park Central,Richmond,Cont...  37.932061 -121.691478   
3    MP: 10.75, SUB: Martinez,Richmond,Contra Costa...  37.767543 -122.171536   
4       3110 regatta Blvd,Richmond,Contra Costa County  37.914071 -122.339687   
..                                                 ...        ...         ...   
828     1306 Channel Blvd,Richmond,Contra Costa County  37.911078 -122.327023   
829  1340 Marina Way South Slip D-141A, D-Dock ,Ric...  37.917326 -122.355774   
830  860 harbour Way South,Richmond,Contra Costa Co...  37.920138 -122.359448   
831  2755 Isaabel St (Isabel Facility),Richmond,Con...  37.897055 -122.321880   
832    3410 Barrett Ave. ,Richmond,Contra Costa County  37.936604 -122.336033   

     Accuracy Score        Accuracy Type         City State   
0              0.90              rooftop  El Sobrante    CA  \
1              0.90              rooftop     Richmond    CA   
2              0.95        street_center    Brentwood    CA   
3              0.70        street_center      Oakland    CA   
4              1.00              rooftop     Richmond    CA   
..              ...                  ...          ...   ...   
828            0.67        street_center     Richmond    CA   
829            1.00  range_interpolation     Richmond    CA   
830            1.00              rooftop     Richmond    CA   
831            1.00  range_interpolation     Richmond    CA   
832            0.95              rooftop     Richmond    CA   

                  County      Zip   
0    Contra Costa County  94803.0  \
1    Contra Costa County  94804.0   
2    Contra Costa County  94513.0   
3         Alameda County  94605.0   
4    Contra Costa County  94804.0   
..                   ...      ...   
828  Contra Costa County  94804.0   
829  Contra Costa County  94804.0   
830  Contra Costa County  94804.0   
831  Contra Costa County  94804.0   
832  Contra Costa County  94805.0   

     ACS Economics/Median household income/Total/Value   
0                                             135063.0  \
1                                              37214.0   
2                                              96607.0   
3                                              75288.0   
4                                             142134.0   
..                                                 ...   
828                                           105945.0   
829                                           107880.0   
830                                           107880.0   
831                                           105945.0   
832                                            88125.0   

     ACS Economics/Median household income/Total/Margin of error   
0                                              23932.0            \
1                                              13731.0             
2                                              62504.0             
3                                              38359.0             
4                                              27685.0             
..                                                 ...             
828                                            10039.0             
829                                            52395.0             
830                                            52395.0             
831                                            10039.0             
832                                            22284.0             

     ACS Demographics/Median age/Total/Value   
0                                       48.0  \
1                                       20.8   
2                                       28.2   
3                                       33.2   
4                                       49.3   
..                                       ...   
828                   

### Check Accuracy Score

In [99]:
geocoded['Accuracy Score'].value_counts().to_frame().sort_values(by=['Accuracy Score'], ascending=False)

count
Accuracy Score       
1.00              394
0.99                7
0.97                2
0.96                1
0.95               29
0.93                1
0.92                4
0.91                2
0.90              119
0.89                3
0.88                3
0.87                1
0.86               11
0.85                8
0.83                3
0.81                1
0.80               35
0.79                1
0.78                3
0.76                5
0.72                1
0.71                1
0.70               79
0.69                4
0.67                3
0.64                1
0.63                1
0.61                1
0.60               12
0.59                1
0.57                1
0.51                1
0.50               21
0.49                1
0.48                2
0.40               29
0.35                2
0.34                1
0.33                3
0.32                1
0.30                9
0.28                5
0.21                1
0.20                3
0.13                2
0.10                5
0.08                2
0.07                1
0.00                6

Most of them are accuracy!

### Merge back to original dataset

In [100]:
address_richmond_geocoded = pd.merge(address_richmond, geocoded, how='left', on='address', validate='m:1')

In [101]:
address_richmond_geocoded

address   Latitude   Longitude   
0    2231 Green Ridge Drive,Richmond,Contra Costa C...  37.963141 -122.296587  \
1          740 Spring St.,Richmond,Contra Costa County  37.922267 -122.335606   
2    Parkway way Drive x Park Central,Richmond,Cont...  37.932061 -121.691478   
3    MP: 10.75, SUB: Martinez,Richmond,Contra Costa...  37.767543 -122.171536   
4       3110 regatta Blvd,Richmond,Contra Costa County  37.914071 -122.339687   
..                                                 ...        ...         ...   
828     1306 Channel Blvd,Richmond,Contra Costa County  37.911078 -122.327023   
829  1340 Marina Way South Slip D-141A, D-Dock ,Ric...  37.917326 -122.355774   
830  860 harbour Way South,Richmond,Contra Costa Co...  37.920138 -122.359448   
831  2755 Isaabel St (Isabel Facility),Richmond,Con...  37.897055 -122.321880   
832    3410 Barrett Ave. ,Richmond,Contra Costa County  37.936604 -122.336033   

     Accuracy Score        Accuracy Type         City State   
0              0.90              rooftop  El Sobrante    CA  \
1              0.90              rooftop     Richmond    CA   
2              0.95        street_center    Brentwood    CA   
3              0.70        street_center      Oakland    CA   
4              1.00              rooftop     Richmond    CA   
..              ...                  ...          ...   ...   
828            0.67        street_center     Richmond    CA   
829            1.00  range_interpolation     Richmond    CA   
830            1.00              rooftop     Richmond    CA   
831            1.00  range_interpolation     Richmond    CA   
832            0.95              rooftop     Richmond    CA   

                  County      Zip   
0    Contra Costa County  94803.0  \
1    Contra Costa County  94804.0   
2    Contra Costa County  94513.0   
3         Alameda County  94605.0   
4    Contra Costa County  94804.0   
..                   ...      ...   
828  Contra Costa County  94804.0   
829  Contra Costa County  94804.0   
830  Contra Costa County  94804.0   
831  Contra Costa County  94804.0   
832  Contra Costa County  94805.0   

     ACS Economics/Median household income/Total/Value   
0                                             135063.0  \
1                                              37214.0   
2                                              96607.0   
3                                              75288.0   
4                                             142134.0   
..                                                 ...   
828                                           105945.0   
829                                           107880.0   
830                                           107880.0   
831                                           105945.0   
832                                            88125.0   

     ACS Economics/Median household income/Total/Margin of error   
0                                              23932.0            \
1                                              13731.0             
2                                              62504.0             
3                                              38359.0             
4                                              27685.0             
..                                                 ...             
828                                            10039.0             
829                                            52395.0             
830                                            52395.0             
831                                            10039.0             
832                                            22284.0             

     ACS Demographics/Median age/Total/Value   
0                                       48.0  \
1                                       20.8   
2                                       28.2   
3                                       33.2   
4                                       49.3   
..                                       ...   
828                   

### Export Geocoded dataset

In [102]:
address_richmond_geocoded.to_csv('address_richmond_geocoded.csv', index=False)